/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Contains basic information about the running application.
 */
@ApiModel(description = "Contains basic information about the running application.")
@JsonPropertyOrder({
  ApplicationInfo.JSON_PROPERTY_NAME,
  ApplicationInfo.JSON_PROPERTY_PACKAGE_NAME,
  ApplicationInfo.JSON_PROPERTY_VERSION,
  ApplicationInfo.JSON_PROPERTY_AUTHORITY_URL,
  ApplicationInfo.JSON_PROPERTY_ALLOW_ANONYMOUS_ROOT_ACCESS,
  ApplicationInfo.JSON_PROPERTY_EXTRA_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ApplicationInfo {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PACKAGE_NAME = "packageName";
  private String packageName;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_AUTHORITY_URL = "authorityUrl";
  private String authorityUrl;

  public static final String JSON_PROPERTY_ALLOW_ANONYMOUS_ROOT_ACCESS = "allowAnonymousRootAccess";
  private Boolean allowAnonymousRootAccess;

  public static final String JSON_PROPERTY_EXTRA_INFO = "extraInfo";
  private Object extraInfo;


  public ApplicationInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the application.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the application.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ApplicationInfo packageName(String packageName) {
    
    this.packageName = packageName;
    return this;
  }

   /**
   * The name of the package the application is running in.
   * @return packageName
  **/
  @ApiModelProperty(required = true, value = "The name of the package the application is running in.")
  @JsonProperty(JSON_PROPERTY_PACKAGE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPackageName() {
    return packageName;
  }


  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }


  public ApplicationInfo version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version of the application.
   * @return version
  **/
  @ApiModelProperty(required = true, value = "The version of the application.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public ApplicationInfo authorityUrl(String authorityUrl) {
    
    this.authorityUrl = authorityUrl;
    return this;
  }

   /**
   * The URL of the IdentityServer that is used for authentication.
   * @return authorityUrl
  **/
  @ApiModelProperty(required = true, value = "The URL of the IdentityServer that is used for authentication.")
  @JsonProperty(JSON_PROPERTY_AUTHORITY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuthorityUrl() {
    return authorityUrl;
  }


  public void setAuthorityUrl(String authorityUrl) {
    this.authorityUrl = authorityUrl;
  }


  public ApplicationInfo allowAnonymousRootAccess(Boolean allowAnonymousRootAccess) {
    
    this.allowAnonymousRootAccess = allowAnonymousRootAccess;
    return this;
  }

   /**
   * Flag indicating whether or not anonymous users are allowed to access the root route.
   * @return allowAnonymousRootAccess
  **/
  @ApiModelProperty(required = true, value = "Flag indicating whether or not anonymous users are allowed to access the root route.")
  @JsonProperty(JSON_PROPERTY_ALLOW_ANONYMOUS_ROOT_ACCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAllowAnonymousRootAccess() {
    return allowAnonymousRootAccess;
  }


  public void setAllowAnonymousRootAccess(Boolean allowAnonymousRootAccess) {
    this.allowAnonymousRootAccess = allowAnonymousRootAccess;
  }


  public ApplicationInfo extraInfo(Object extraInfo) {
    
    this.extraInfo = extraInfo;
    return this;
  }

   /**
   * Contains additional information about the application.
   * @return extraInfo
  **/
  @ApiModelProperty(required = true, value = "Contains additional information about the application.")
  @JsonProperty(JSON_PROPERTY_EXTRA_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getExtraInfo() {
    return extraInfo;
  }


  public void setExtraInfo(Object extraInfo) {
    this.extraInfo = extraInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationInfo applicationInfo = (ApplicationInfo) o;
    return Objects.equals(this.name, applicationInfo.name) &&
        Objects.equals(this.packageName, applicationInfo.packageName) &&
        Objects.equals(this.version, applicationInfo.version) &&
        Objects.equals(this.authorityUrl, applicationInfo.authorityUrl) &&
        Objects.equals(this.allowAnonymousRootAccess, applicationInfo.allowAnonymousRootAccess) &&
        Objects.equals(this.extraInfo, applicationInfo.extraInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, packageName, version, authorityUrl, allowAnonymousRootAccess, extraInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    authorityUrl: ").append(toIndentedString(authorityUrl)).append("\n");
    sb.append("    allowAnonymousRootAccess: ").append(toIndentedString(allowAnonymousRootAccess)).append("\n");
    sb.append("    extraInfo: ").append(toIndentedString(extraInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

