/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A BaseElement.
 */
@ApiModel(description = "A BaseElement.")
@JsonPropertyOrder({
  BaseElementViewModel.JSON_PROPERTY_ID,
  BaseElementViewModel.JSON_PROPERTY_CUSTOM_PROPERTIES,
  BaseElementViewModel.JSON_PROPERTY_DOCUMENTATION,
  BaseElementViewModel.JSON_PROPERTY_PROCESS_MODEL_ID,
  BaseElementViewModel.JSON_PROPERTY_PROCESS_MODEL_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class BaseElementViewModel {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CUSTOM_PROPERTIES = "customProperties";
  private Map<String, String> customProperties = new HashMap<String, String>();

  public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
  private List<String> documentation = null;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_NAME = "processModelName";
  private String processModelName;


  public BaseElementViewModel id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the BaseElement.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The ID of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BaseElementViewModel customProperties(Map<String, String> customProperties) {
    
    this.customProperties = customProperties;
    return this;
  }

  public BaseElementViewModel putCustomPropertiesItem(String key, String customPropertiesItem) {
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * The custom properties of the BaseElement.
   * @return customProperties
  **/
  @ApiModelProperty(required = true, value = "The custom properties of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, String> getCustomProperties() {
    return customProperties;
  }


  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }


  public BaseElementViewModel documentation(List<String> documentation) {
    
    this.documentation = documentation;
    return this;
  }

  public BaseElementViewModel addDocumentationItem(String documentationItem) {
    if (this.documentation == null) {
      this.documentation = new ArrayList<String>();
    }
    this.documentation.add(documentationItem);
    return this;
  }

   /**
   * The documentation of the BaseElement.
   * @return documentation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The documentation of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDocumentation() {
    return documentation;
  }


  public void setDocumentation(List<String> documentation) {
    this.documentation = documentation;
  }


  public BaseElementViewModel processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel that contains the BaseElement.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel that contains the BaseElement.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public BaseElementViewModel processModelName(String processModelName) {
    
    this.processModelName = processModelName;
    return this;
  }

   /**
   * The name of the ProcessModel that contains the BaseElement.
   * @return processModelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the ProcessModel that contains the BaseElement.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessModelName() {
    return processModelName;
  }


  public void setProcessModelName(String processModelName) {
    this.processModelName = processModelName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseElementViewModel baseElementViewModel = (BaseElementViewModel) o;
    return Objects.equals(this.id, baseElementViewModel.id) &&
        Objects.equals(this.customProperties, baseElementViewModel.customProperties) &&
        Objects.equals(this.documentation, baseElementViewModel.documentation) &&
        Objects.equals(this.processModelId, baseElementViewModel.processModelId) &&
        Objects.equals(this.processModelName, baseElementViewModel.processModelName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customProperties, documentation, processModelId, processModelName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseElementViewModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    processModelName: ").append(toIndentedString(processModelName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

