/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of a BPMN element.
 */
public enum BpmnType {
  
  TASK("bpmn:Task"),
  
  BUSINESSRULETASK("bpmn:BusinessRuleTask"),
  
  USERTASK("bpmn:UserTask"),
  
  EXCLUSIVEGATEWAY("bpmn:ExclusiveGateway"),
  
  PARALLELGATEWAY("bpmn:ParallelGateway"),
  
  SERVICETASK("bpmn:ServiceTask"),
  
  STARTEVENT("bpmn:StartEvent"),
  
  ENDEVENT("bpmn:EndEvent"),
  
  INTERMEDIATECATCHEVENT("bpmn:IntermediateCatchEvent"),
  
  INTERMEDIATETHROWEVENT("bpmn:IntermediateThrowEvent"),
  
  SCRIPTTASK("bpmn:ScriptTask"),
  
  BOUNDARYEVENT("bpmn:BoundaryEvent"),
  
  CALLACTIVITY("bpmn:CallActivity"),
  
  SUBPROCESS("bpmn:SubProcess"),
  
  MANUALTASK("bpmn:ManualTask"),
  
  COMPLEXGATEWAY("bpmn:ComplexGateway"),
  
  INCLUSIVEGATEWAY("bpmn:InclusiveGateway"),
  
  EVENTBASEDGATEWAY("bpmn:EventBasedGateway"),
  
  SENDTASK("bpmn:SendTask"),
  
  RECEIVETASK("bpmn:ReceiveTask");

  private String value;

  BpmnType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BpmnType fromValue(String value) {
    for (BpmnType b : BpmnType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

