/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ProcessInstance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A Correlation.
 */
@ApiModel(description = "A Correlation.")
@JsonPropertyOrder({
  Correlation.JSON_PROPERTY_CORRELATION_ID,
  Correlation.JSON_PROPERTY_METADATA,
  Correlation.JSON_PROPERTY_PROCESS_INSTANCES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class Correlation {
  public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
  private String correlationId;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, String> metadata = null;

  public static final String JSON_PROPERTY_PROCESS_INSTANCES = "processInstances";
  private List<ProcessInstance> processInstances = null;


  public Correlation correlationId(String correlationId) {
    
    this.correlationId = correlationId;
    return this;
  }

   /**
   * The id of the correlation.
   * @return correlationId
  **/
  @ApiModelProperty(required = true, value = "The id of the correlation.")
  @JsonProperty(JSON_PROPERTY_CORRELATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCorrelationId() {
    return correlationId;
  }


  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }


  public Correlation metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public Correlation putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<String, String>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Metadata for a correlation.
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Metadata for a correlation.")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public Correlation processInstances(List<ProcessInstance> processInstances) {
    
    this.processInstances = processInstances;
    return this;
  }

  public Correlation addProcessInstancesItem(ProcessInstance processInstancesItem) {
    if (this.processInstances == null) {
      this.processInstances = new ArrayList<ProcessInstance>();
    }
    this.processInstances.add(processInstancesItem);
    return this;
  }

   /**
   * The process instances that run in the context of this correlation.
   * @return processInstances
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The process instances that run in the context of this correlation.")
  @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProcessInstance> getProcessInstances() {
    return processInstances;
  }


  public void setProcessInstances(List<ProcessInstance> processInstances) {
    this.processInstances = processInstances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Correlation correlation = (Correlation) o;
    return Objects.equals(this.correlationId, correlation.correlationId) &&
        Objects.equals(this.metadata, correlation.metadata) &&
        Objects.equals(this.processInstances, correlation.processInstances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(correlationId, metadata, processInstances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Correlation {\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    processInstances: ").append(toIndentedString(processInstances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

