/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ActiveCronjob;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A list of active cronjobs.
 */
@ApiModel(description = "A list of active cronjobs.")
@JsonPropertyOrder({
  CronjobList.JSON_PROPERTY_CRONJOBS,
  CronjobList.JSON_PROPERTY_TOTAL_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class CronjobList {
  public static final String JSON_PROPERTY_CRONJOBS = "cronjobs";
  private List<ActiveCronjob> cronjobs = new ArrayList<ActiveCronjob>();

  public static final String JSON_PROPERTY_TOTAL_COUNT = "totalCount";
  private BigDecimal totalCount;


  public CronjobList cronjobs(List<ActiveCronjob> cronjobs) {
    
    this.cronjobs = cronjobs;
    return this;
  }

  public CronjobList addCronjobsItem(ActiveCronjob cronjobsItem) {
    this.cronjobs.add(cronjobsItem);
    return this;
  }

   /**
   * The active cronjobs
   * @return cronjobs
  **/
  @ApiModelProperty(required = true, value = "The active cronjobs")
  @JsonProperty(JSON_PROPERTY_CRONJOBS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ActiveCronjob> getCronjobs() {
    return cronjobs;
  }


  public void setCronjobs(List<ActiveCronjob> cronjobs) {
    this.cronjobs = cronjobs;
  }


  public CronjobList totalCount(BigDecimal totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * The total number of active cronjobs
   * @return totalCount
  **/
  @ApiModelProperty(required = true, value = "The total number of active cronjobs")
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(BigDecimal totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CronjobList cronjobList = (CronjobList) o;
    return Objects.equals(this.cronjobs, cronjobList.cronjobs) &&
        Objects.equals(this.totalCount, cronjobList.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cronjobs, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CronjobList {\n");
    sb.append("    cronjobs: ").append(toIndentedString(cronjobs)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

