/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Describes a single Cronjob. Used as payload for the CronjobEventMessage.
 */
@ApiModel(description = "Describes a single Cronjob. Used as payload for the CronjobEventMessage.")
@JsonPropertyOrder({
  CronjobEvent.JSON_PROPERTY_START_EVENT_ID,
  CronjobEvent.JSON_PROPERTY_PROCESS_MODEL_ID,
  CronjobEvent.JSON_PROPERTY_CRONJOB
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class CronjobEvent {
  public static final String JSON_PROPERTY_START_EVENT_ID = "startEventId";
  private String startEventId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_CRONJOB = "cronjob";
  private String cronjob;


  public CronjobEvent startEventId(String startEventId) {
    
    this.startEventId = startEventId;
    return this;
  }

   /**
   * The ID of the StartEvent that contains the cronjob.
   * @return startEventId
  **/
  @ApiModelProperty(required = true, value = "The ID of the StartEvent that contains the cronjob.")
  @JsonProperty(JSON_PROPERTY_START_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartEventId() {
    return startEventId;
  }


  public void setStartEventId(String startEventId) {
    this.startEventId = startEventId;
  }


  public CronjobEvent processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel that contains the cronjob.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel that contains the cronjob.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public CronjobEvent cronjob(String cronjob) {
    
    this.cronjob = cronjob;
    return this;
  }

   /**
   * The crontab that describs the cronjob.
   * @return cronjob
  **/
  @ApiModelProperty(required = true, value = "The crontab that describs the cronjob.")
  @JsonProperty(JSON_PROPERTY_CRONJOB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCronjob() {
    return cronjob;
  }


  public void setCronjob(String cronjob) {
    this.cronjob = cronjob;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CronjobEvent cronjobEvent = (CronjobEvent) o;
    return Objects.equals(this.startEventId, cronjobEvent.startEventId) &&
        Objects.equals(this.processModelId, cronjobEvent.processModelId) &&
        Objects.equals(this.cronjob, cronjobEvent.cronjob);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startEventId, processModelId, cronjob);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CronjobEvent {\n");
    sb.append("    startEventId: ").append(toIndentedString(startEventId)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    cronjob: ").append(toIndentedString(cronjob)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

