/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.CronjobEvent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A message that is sent when a cronjob related event was triggered.
 */
@ApiModel(description = "A message that is sent when a cronjob related event was triggered.")
@JsonPropertyOrder({
  CronjobEventMessage.JSON_PROPERTY_PROCESS_DEFINITION_ID,
  CronjobEventMessage.JSON_PROPERTY_CRONJOBS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class CronjobEventMessage {
  public static final String JSON_PROPERTY_PROCESS_DEFINITION_ID = "processDefinitionId";
  private String processDefinitionId;

  public static final String JSON_PROPERTY_CRONJOBS = "cronjobs";
  private List<CronjobEvent> cronjobs = new ArrayList<CronjobEvent>();


  public CronjobEventMessage processDefinitionId(String processDefinitionId) {
    
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * The ID of the ProcessDefinition that contains the cronjob.
   * @return processDefinitionId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessDefinition that contains the cronjob.")
  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessDefinitionId() {
    return processDefinitionId;
  }


  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }


  public CronjobEventMessage cronjobs(List<CronjobEvent> cronjobs) {
    
    this.cronjobs = cronjobs;
    return this;
  }

  public CronjobEventMessage addCronjobsItem(CronjobEvent cronjobsItem) {
    this.cronjobs.add(cronjobsItem);
    return this;
  }

   /**
   * The cronjobs that were triggered.
   * @return cronjobs
  **/
  @ApiModelProperty(required = true, value = "The cronjobs that were triggered.")
  @JsonProperty(JSON_PROPERTY_CRONJOBS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CronjobEvent> getCronjobs() {
    return cronjobs;
  }


  public void setCronjobs(List<CronjobEvent> cronjobs) {
    this.cronjobs = cronjobs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CronjobEventMessage cronjobEventMessage = (CronjobEventMessage) o;
    return Objects.equals(this.processDefinitionId, cronjobEventMessage.processDefinitionId) &&
        Objects.equals(this.cronjobs, cronjobEventMessage.cronjobs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processDefinitionId, cronjobs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CronjobEventMessage {\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    cronjobs: ").append(toIndentedString(cronjobs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

