/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Describes a data object instance.
 */
@ApiModel(description = "Describes a data object instance.")
@JsonPropertyOrder({
  DataObjectInstance.JSON_PROPERTY_DATA_OBJECT_ID,
  DataObjectInstance.JSON_PROPERTY_PROCESS_DEFINITION_ID,
  DataObjectInstance.JSON_PROPERTY_PROCESS_MODEL_ID,
  DataObjectInstance.JSON_PROPERTY_PROCESS_INSTANCE_ID,
  DataObjectInstance.JSON_PROPERTY_FLOW_NODE_INSTANCE_ID,
  DataObjectInstance.JSON_PROPERTY_VALUE,
  DataObjectInstance.JSON_PROPERTY_CREATED_AT,
  DataObjectInstance.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class DataObjectInstance {
  public static final String JSON_PROPERTY_DATA_OBJECT_ID = "dataObjectId";
  private String dataObjectId;

  public static final String JSON_PROPERTY_PROCESS_DEFINITION_ID = "processDefinitionId";
  private String processDefinitionId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_PROCESS_INSTANCE_ID = "processInstanceId";
  private String processInstanceId;

  public static final String JSON_PROPERTY_FLOW_NODE_INSTANCE_ID = "flowNodeInstanceId";
  private String flowNodeInstanceId;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Object value;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private String createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private String updatedAt;


  public DataObjectInstance dataObjectId(String dataObjectId) {
    
    this.dataObjectId = dataObjectId;
    return this;
  }

   /**
   * The ID of the data object
   * @return dataObjectId
  **/
  @ApiModelProperty(required = true, value = "The ID of the data object")
  @JsonProperty(JSON_PROPERTY_DATA_OBJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDataObjectId() {
    return dataObjectId;
  }


  public void setDataObjectId(String dataObjectId) {
    this.dataObjectId = dataObjectId;
  }


  public DataObjectInstance processDefinitionId(String processDefinitionId) {
    
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * The ID of the process definition that contains the data object
   * @return processDefinitionId
  **/
  @ApiModelProperty(required = true, value = "The ID of the process definition that contains the data object")
  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessDefinitionId() {
    return processDefinitionId;
  }


  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }


  public DataObjectInstance processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the process model that contains the data object
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the process model that contains the data object")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public DataObjectInstance processInstanceId(String processInstanceId) {
    
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * The ID of the process instance that contains the data object
   * @return processInstanceId
  **/
  @ApiModelProperty(required = true, value = "The ID of the process instance that contains the data object")
  @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessInstanceId() {
    return processInstanceId;
  }


  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }


  public DataObjectInstance flowNodeInstanceId(String flowNodeInstanceId) {
    
    this.flowNodeInstanceId = flowNodeInstanceId;
    return this;
  }

   /**
   * The ID of the FlowNodeInstance that contains the data object
   * @return flowNodeInstanceId
  **/
  @ApiModelProperty(required = true, value = "The ID of the FlowNodeInstance that contains the data object")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlowNodeInstanceId() {
    return flowNodeInstanceId;
  }


  public void setFlowNodeInstanceId(String flowNodeInstanceId) {
    this.flowNodeInstanceId = flowNodeInstanceId;
  }


  public DataObjectInstance value(Object value) {
    
    this.value = value;
    return this;
  }

   /**
   * The value of the data object
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The value of the data object")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getValue() {
    return value;
  }


  public void setValue(Object value) {
    this.value = value;
  }


  public DataObjectInstance createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The Date the data object instance was created
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "The Date the data object instance was created")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public DataObjectInstance updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The Date the data object instance was last updated
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "The Date the data object instance was last updated")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataObjectInstance dataObjectInstance = (DataObjectInstance) o;
    return Objects.equals(this.dataObjectId, dataObjectInstance.dataObjectId) &&
        Objects.equals(this.processDefinitionId, dataObjectInstance.processDefinitionId) &&
        Objects.equals(this.processModelId, dataObjectInstance.processModelId) &&
        Objects.equals(this.processInstanceId, dataObjectInstance.processInstanceId) &&
        Objects.equals(this.flowNodeInstanceId, dataObjectInstance.flowNodeInstanceId) &&
        Objects.equals(this.value, dataObjectInstance.value) &&
        Objects.equals(this.createdAt, dataObjectInstance.createdAt) &&
        Objects.equals(this.updatedAt, dataObjectInstance.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataObjectId, processDefinitionId, processModelId, processInstanceId, flowNodeInstanceId, value, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataObjectInstance {\n");
    sb.append("    dataObjectId: ").append(toIndentedString(dataObjectId)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    flowNodeInstanceId: ").append(toIndentedString(flowNodeInstanceId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

