/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.DataObjectInstance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A list of data object instances.
 */
@ApiModel(description = "A list of data object instances.")
@JsonPropertyOrder({
  DataObjectInstanceList.JSON_PROPERTY_DATA_OBJECT_INSTANCES,
  DataObjectInstanceList.JSON_PROPERTY_TOTAL_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class DataObjectInstanceList {
  public static final String JSON_PROPERTY_DATA_OBJECT_INSTANCES = "dataObjectInstances";
  private List<DataObjectInstance> dataObjectInstances = new ArrayList<DataObjectInstance>();

  public static final String JSON_PROPERTY_TOTAL_COUNT = "totalCount";
  private BigDecimal totalCount;


  public DataObjectInstanceList dataObjectInstances(List<DataObjectInstance> dataObjectInstances) {
    
    this.dataObjectInstances = dataObjectInstances;
    return this;
  }

  public DataObjectInstanceList addDataObjectInstancesItem(DataObjectInstance dataObjectInstancesItem) {
    this.dataObjectInstances.add(dataObjectInstancesItem);
    return this;
  }

   /**
   * The data object instances
   * @return dataObjectInstances
  **/
  @ApiModelProperty(required = true, value = "The data object instances")
  @JsonProperty(JSON_PROPERTY_DATA_OBJECT_INSTANCES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<DataObjectInstance> getDataObjectInstances() {
    return dataObjectInstances;
  }


  public void setDataObjectInstances(List<DataObjectInstance> dataObjectInstances) {
    this.dataObjectInstances = dataObjectInstances;
  }


  public DataObjectInstanceList totalCount(BigDecimal totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * The total number of data object instances
   * @return totalCount
  **/
  @ApiModelProperty(required = true, value = "The total number of data object instances")
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(BigDecimal totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataObjectInstanceList dataObjectInstanceList = (DataObjectInstanceList) o;
    return Objects.equals(this.dataObjectInstances, dataObjectInstanceList.dataObjectInstances) &&
        Objects.equals(this.totalCount, dataObjectInstanceList.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataObjectInstances, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataObjectInstanceList {\n");
    sb.append("    dataObjectInstances: ").append(toIndentedString(dataObjectInstances)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

