/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.BpmnType;
import io.miragon.processcube.client.model.EndEventViewModelAllOf;
import io.miragon.processcube.client.model.EventViewModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * An EndEvent.
 */
@ApiModel(description = "An EndEvent.")
@JsonPropertyOrder({
  EndEventViewModel.JSON_PROPERTY_ID,
  EndEventViewModel.JSON_PROPERTY_CUSTOM_PROPERTIES,
  EndEventViewModel.JSON_PROPERTY_DOCUMENTATION,
  EndEventViewModel.JSON_PROPERTY_PROCESS_MODEL_ID,
  EndEventViewModel.JSON_PROPERTY_PROCESS_MODEL_NAME,
  EndEventViewModel.JSON_PROPERTY_NAME,
  EndEventViewModel.JSON_PROPERTY_FLOW_NODE_TYPE,
  EndEventViewModel.JSON_PROPERTY_ERROR_NAME,
  EndEventViewModel.JSON_PROPERTY_ERROR_CODE,
  EndEventViewModel.JSON_PROPERTY_ERROR_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class EndEventViewModel {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CUSTOM_PROPERTIES = "customProperties";
  private Map<String, String> customProperties = new HashMap<String, String>();

  public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
  private List<String> documentation = null;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_NAME = "processModelName";
  private String processModelName;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_FLOW_NODE_TYPE = "flowNodeType";
  private BpmnType flowNodeType;

  public static final String JSON_PROPERTY_ERROR_NAME = "errorName";
  private String errorName;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  private String errorMessage;


  public EndEventViewModel id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the BaseElement.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The ID of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public EndEventViewModel customProperties(Map<String, String> customProperties) {
    
    this.customProperties = customProperties;
    return this;
  }

  public EndEventViewModel putCustomPropertiesItem(String key, String customPropertiesItem) {
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * The custom properties of the BaseElement.
   * @return customProperties
  **/
  @ApiModelProperty(required = true, value = "The custom properties of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, String> getCustomProperties() {
    return customProperties;
  }


  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }


  public EndEventViewModel documentation(List<String> documentation) {
    
    this.documentation = documentation;
    return this;
  }

  public EndEventViewModel addDocumentationItem(String documentationItem) {
    if (this.documentation == null) {
      this.documentation = new ArrayList<String>();
    }
    this.documentation.add(documentationItem);
    return this;
  }

   /**
   * The documentation of the BaseElement.
   * @return documentation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The documentation of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDocumentation() {
    return documentation;
  }


  public void setDocumentation(List<String> documentation) {
    this.documentation = documentation;
  }


  public EndEventViewModel processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel that contains the BaseElement.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel that contains the BaseElement.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public EndEventViewModel processModelName(String processModelName) {
    
    this.processModelName = processModelName;
    return this;
  }

   /**
   * The name of the ProcessModel that contains the BaseElement.
   * @return processModelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the ProcessModel that contains the BaseElement.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessModelName() {
    return processModelName;
  }


  public void setProcessModelName(String processModelName) {
    this.processModelName = processModelName;
  }


  public EndEventViewModel name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the FlowNode.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the FlowNode.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public EndEventViewModel flowNodeType(BpmnType flowNodeType) {
    
    this.flowNodeType = flowNodeType;
    return this;
  }

   /**
   * Get flowNodeType
   * @return flowNodeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BpmnType getFlowNodeType() {
    return flowNodeType;
  }


  public void setFlowNodeType(BpmnType flowNodeType) {
    this.flowNodeType = flowNodeType;
  }


  public EndEventViewModel errorName(String errorName) {
    
    this.errorName = errorName;
    return this;
  }

   /**
   * The name of the error.
   * @return errorName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the error.")
  @JsonProperty(JSON_PROPERTY_ERROR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorName() {
    return errorName;
  }


  public void setErrorName(String errorName) {
    this.errorName = errorName;
  }


  public EndEventViewModel errorCode(String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * The code of the error.
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The code of the error.")
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  public EndEventViewModel errorMessage(String errorMessage) {
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * The message of the error.
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The message of the error.")
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorMessage() {
    return errorMessage;
  }


  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndEventViewModel endEventViewModel = (EndEventViewModel) o;
    return Objects.equals(this.id, endEventViewModel.id) &&
        Objects.equals(this.customProperties, endEventViewModel.customProperties) &&
        Objects.equals(this.documentation, endEventViewModel.documentation) &&
        Objects.equals(this.processModelId, endEventViewModel.processModelId) &&
        Objects.equals(this.processModelName, endEventViewModel.processModelName) &&
        Objects.equals(this.name, endEventViewModel.name) &&
        Objects.equals(this.flowNodeType, endEventViewModel.flowNodeType) &&
        Objects.equals(this.errorName, endEventViewModel.errorName) &&
        Objects.equals(this.errorCode, endEventViewModel.errorCode) &&
        Objects.equals(this.errorMessage, endEventViewModel.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customProperties, documentation, processModelId, processModelName, name, flowNodeType, errorName, errorCode, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndEventViewModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    processModelName: ").append(toIndentedString(processModelName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    flowNodeType: ").append(toIndentedString(flowNodeType)).append("\n");
    sb.append("    errorName: ").append(toIndentedString(errorName)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

