/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * EndEventViewModelAllOf
 */
@JsonPropertyOrder({
  EndEventViewModelAllOf.JSON_PROPERTY_ERROR_NAME,
  EndEventViewModelAllOf.JSON_PROPERTY_ERROR_CODE,
  EndEventViewModelAllOf.JSON_PROPERTY_ERROR_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class EndEventViewModelAllOf {
  public static final String JSON_PROPERTY_ERROR_NAME = "errorName";
  private String errorName;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  private String errorMessage;


  public EndEventViewModelAllOf errorName(String errorName) {
    
    this.errorName = errorName;
    return this;
  }

   /**
   * The name of the error.
   * @return errorName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the error.")
  @JsonProperty(JSON_PROPERTY_ERROR_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorName() {
    return errorName;
  }


  public void setErrorName(String errorName) {
    this.errorName = errorName;
  }


  public EndEventViewModelAllOf errorCode(String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * The code of the error.
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The code of the error.")
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  public EndEventViewModelAllOf errorMessage(String errorMessage) {
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * The message of the error.
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The message of the error.")
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorMessage() {
    return errorMessage;
  }


  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndEventViewModelAllOf endEventViewModelAllOf = (EndEventViewModelAllOf) o;
    return Objects.equals(this.errorName, endEventViewModelAllOf.errorName) &&
        Objects.equals(this.errorCode, endEventViewModelAllOf.errorCode) &&
        Objects.equals(this.errorMessage, endEventViewModelAllOf.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorName, errorCode, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndEventViewModelAllOf {\n");
    sb.append("    errorName: ").append(toIndentedString(errorName)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

