/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.BpmnType;
import io.miragon.processcube.client.model.EventType;
import io.miragon.processcube.client.model.ExternalTaskCreatedMessage;
import io.miragon.processcube.client.model.ExternalTaskSuccessMessageAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Message that is sent whenever an ExternalTask encountered an error.
 */
@ApiModel(description = "Message that is sent whenever an ExternalTask encountered an error.")
@JsonPropertyOrder({
  ExternalTaskSuccessMessage.JSON_PROPERTY_CORRELATION_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_PROCESS_DEFINITION_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_PROCESS_MODEL_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_PROCESS_MODEL_NAME,
  ExternalTaskSuccessMessage.JSON_PROPERTY_PROCESS_INSTANCE_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_PARENT_PROCESS_INSTANCE_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_FLOW_NODE_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_FLOW_NODE_NAME,
  ExternalTaskSuccessMessage.JSON_PROPERTY_FLOW_NODE_TYPE,
  ExternalTaskSuccessMessage.JSON_PROPERTY_FLOW_NODE_INSTANCE_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_OWNER_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_PREVIOUS_FLOW_NODE_INSTANCE_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_CURRENT_TOKEN,
  ExternalTaskSuccessMessage.JSON_PROPERTY_EVENT_TYPE,
  ExternalTaskSuccessMessage.JSON_PROPERTY_EVENT_NAME,
  ExternalTaskSuccessMessage.JSON_PROPERTY_CUSTOM_CORRELATION_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_EXTERNAL_TASK_ID,
  ExternalTaskSuccessMessage.JSON_PROPERTY_TOPIC,
  ExternalTaskSuccessMessage.JSON_PROPERTY_IS_SINGLE_TRY,
  ExternalTaskSuccessMessage.JSON_PROPERTY_RESULT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ExternalTaskSuccessMessage {
  public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
  private String correlationId;

  public static final String JSON_PROPERTY_PROCESS_DEFINITION_ID = "processDefinitionId";
  private String processDefinitionId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_NAME = "processModelName";
  private String processModelName;

  public static final String JSON_PROPERTY_PROCESS_INSTANCE_ID = "processInstanceId";
  private String processInstanceId;

  public static final String JSON_PROPERTY_PARENT_PROCESS_INSTANCE_ID = "parentProcessInstanceId";
  private String parentProcessInstanceId;

  public static final String JSON_PROPERTY_FLOW_NODE_ID = "flowNodeId";
  private String flowNodeId;

  public static final String JSON_PROPERTY_FLOW_NODE_NAME = "flowNodeName";
  private String flowNodeName;

  public static final String JSON_PROPERTY_FLOW_NODE_TYPE = "flowNodeType";
  private BpmnType flowNodeType;

  public static final String JSON_PROPERTY_FLOW_NODE_INSTANCE_ID = "flowNodeInstanceId";
  private String flowNodeInstanceId;

  public static final String JSON_PROPERTY_OWNER_ID = "ownerId";
  private String ownerId;

  public static final String JSON_PROPERTY_PREVIOUS_FLOW_NODE_INSTANCE_ID = "previousFlowNodeInstanceId";
  private String previousFlowNodeInstanceId;

  public static final String JSON_PROPERTY_CURRENT_TOKEN = "currentToken";
  private Object currentToken;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  private EventType eventType;

  public static final String JSON_PROPERTY_EVENT_NAME = "eventName";
  private String eventName;

  public static final String JSON_PROPERTY_CUSTOM_CORRELATION_ID = "customCorrelationId";
  private String customCorrelationId;

  public static final String JSON_PROPERTY_EXTERNAL_TASK_ID = "externalTaskId";
  private String externalTaskId;

  public static final String JSON_PROPERTY_TOPIC = "topic";
  private String topic;

  public static final String JSON_PROPERTY_IS_SINGLE_TRY = "isSingleTry";
  private Boolean isSingleTry;

  public static final String JSON_PROPERTY_RESULT = "result";
  private Object result;


  public ExternalTaskSuccessMessage correlationId(String correlationId) {
    
    this.correlationId = correlationId;
    return this;
  }

   /**
   * The ID of the correlation that the event belongs to.
   * @return correlationId
  **/
  @ApiModelProperty(required = true, value = "The ID of the correlation that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_CORRELATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCorrelationId() {
    return correlationId;
  }


  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }


  public ExternalTaskSuccessMessage processDefinitionId(String processDefinitionId) {
    
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * The ID of the ProcessDefinition that the event belongs to.
   * @return processDefinitionId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessDefinition that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessDefinitionId() {
    return processDefinitionId;
  }


  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }


  public ExternalTaskSuccessMessage processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel that the event belongs to.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public ExternalTaskSuccessMessage processModelName(String processModelName) {
    
    this.processModelName = processModelName;
    return this;
  }

   /**
   * The name of the ProcessModel that the event belongs to.
   * @return processModelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the ProcessModel that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessModelName() {
    return processModelName;
  }


  public void setProcessModelName(String processModelName) {
    this.processModelName = processModelName;
  }


  public ExternalTaskSuccessMessage processInstanceId(String processInstanceId) {
    
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * The ID of the ProcessInstance that the event belongs to.
   * @return processInstanceId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessInstance that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessInstanceId() {
    return processInstanceId;
  }


  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }


  public ExternalTaskSuccessMessage parentProcessInstanceId(String parentProcessInstanceId) {
    
    this.parentProcessInstanceId = parentProcessInstanceId;
    return this;
  }

   /**
   * The ID of the parent ProcessInstance (if event occured in a sub process)
   * @return parentProcessInstanceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the parent ProcessInstance (if event occured in a sub process)")
  @JsonProperty(JSON_PROPERTY_PARENT_PROCESS_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentProcessInstanceId() {
    return parentProcessInstanceId;
  }


  public void setParentProcessInstanceId(String parentProcessInstanceId) {
    this.parentProcessInstanceId = parentProcessInstanceId;
  }


  public ExternalTaskSuccessMessage flowNodeId(String flowNodeId) {
    
    this.flowNodeId = flowNodeId;
    return this;
  }

   /**
   * The ID of the FlowNode that the event belongs to.
   * @return flowNodeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the FlowNode that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowNodeId() {
    return flowNodeId;
  }


  public void setFlowNodeId(String flowNodeId) {
    this.flowNodeId = flowNodeId;
  }


  public ExternalTaskSuccessMessage flowNodeName(String flowNodeName) {
    
    this.flowNodeName = flowNodeName;
    return this;
  }

   /**
   * The name of the FlowNode that the event belongs to.
   * @return flowNodeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the FlowNode that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowNodeName() {
    return flowNodeName;
  }


  public void setFlowNodeName(String flowNodeName) {
    this.flowNodeName = flowNodeName;
  }


  public ExternalTaskSuccessMessage flowNodeType(BpmnType flowNodeType) {
    
    this.flowNodeType = flowNodeType;
    return this;
  }

   /**
   * Get flowNodeType
   * @return flowNodeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BpmnType getFlowNodeType() {
    return flowNodeType;
  }


  public void setFlowNodeType(BpmnType flowNodeType) {
    this.flowNodeType = flowNodeType;
  }


  public ExternalTaskSuccessMessage flowNodeInstanceId(String flowNodeInstanceId) {
    
    this.flowNodeInstanceId = flowNodeInstanceId;
    return this;
  }

   /**
   * The ID of the FlowNodeInstance that the event belongs to.
   * @return flowNodeInstanceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the FlowNodeInstance that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowNodeInstanceId() {
    return flowNodeInstanceId;
  }


  public void setFlowNodeInstanceId(String flowNodeInstanceId) {
    this.flowNodeInstanceId = flowNodeInstanceId;
  }


  public ExternalTaskSuccessMessage ownerId(String ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * The ID of the user that owns the ProcessInstance that the event belongs to.
   * @return ownerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the user that owns the ProcessInstance that the event belongs to.")
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  public ExternalTaskSuccessMessage previousFlowNodeInstanceId(String previousFlowNodeInstanceId) {
    
    this.previousFlowNodeInstanceId = previousFlowNodeInstanceId;
    return this;
  }

   /**
   * The ID of the FlowNodeInstance that was executed before.
   * @return previousFlowNodeInstanceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the FlowNodeInstance that was executed before.")
  @JsonProperty(JSON_PROPERTY_PREVIOUS_FLOW_NODE_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviousFlowNodeInstanceId() {
    return previousFlowNodeInstanceId;
  }


  public void setPreviousFlowNodeInstanceId(String previousFlowNodeInstanceId) {
    this.previousFlowNodeInstanceId = previousFlowNodeInstanceId;
  }


  public ExternalTaskSuccessMessage currentToken(Object currentToken) {
    
    this.currentToken = currentToken;
    return this;
  }

   /**
   * The current token of the ProcessInstance.
   * @return currentToken
  **/
  @ApiModelProperty(required = true, value = "The current token of the ProcessInstance.")
  @JsonProperty(JSON_PROPERTY_CURRENT_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCurrentToken() {
    return currentToken;
  }


  public void setCurrentToken(Object currentToken) {
    this.currentToken = currentToken;
  }


  public ExternalTaskSuccessMessage eventType(EventType eventType) {
    
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventType getEventType() {
    return eventType;
  }


  public void setEventType(EventType eventType) {
    this.eventType = eventType;
  }


  public ExternalTaskSuccessMessage eventName(String eventName) {
    
    this.eventName = eventName;
    return this;
  }

   /**
   * The name of the event.
   * @return eventName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the event.")
  @JsonProperty(JSON_PROPERTY_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventName() {
    return eventName;
  }


  public void setEventName(String eventName) {
    this.eventName = eventName;
  }


  public ExternalTaskSuccessMessage customCorrelationId(String customCorrelationId) {
    
    this.customCorrelationId = customCorrelationId;
    return this;
  }

   /**
   * Process Instances triggered by this Message will use the following Correlation ID.
   * @return customCorrelationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Process Instances triggered by this Message will use the following Correlation ID.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_CORRELATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomCorrelationId() {
    return customCorrelationId;
  }


  public void setCustomCorrelationId(String customCorrelationId) {
    this.customCorrelationId = customCorrelationId;
  }


  public ExternalTaskSuccessMessage externalTaskId(String externalTaskId) {
    
    this.externalTaskId = externalTaskId;
    return this;
  }

   /**
   * The ID of the ExternalTask.
   * @return externalTaskId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ExternalTask.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_TASK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalTaskId() {
    return externalTaskId;
  }


  public void setExternalTaskId(String externalTaskId) {
    this.externalTaskId = externalTaskId;
  }


  public ExternalTaskSuccessMessage topic(String topic) {
    
    this.topic = topic;
    return this;
  }

   /**
   * The topic of the ExternalTask.
   * @return topic
  **/
  @ApiModelProperty(required = true, value = "The topic of the ExternalTask.")
  @JsonProperty(JSON_PROPERTY_TOPIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTopic() {
    return topic;
  }


  public void setTopic(String topic) {
    this.topic = topic;
  }


  public ExternalTaskSuccessMessage isSingleTry(Boolean isSingleTry) {
    
    this.isSingleTry = isSingleTry;
    return this;
  }

   /**
   * Flag indicating whether the ExternalTask is a SingleTry ExternalTask.
   * @return isSingleTry
  **/
  @ApiModelProperty(required = true, value = "Flag indicating whether the ExternalTask is a SingleTry ExternalTask.")
  @JsonProperty(JSON_PROPERTY_IS_SINGLE_TRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsSingleTry() {
    return isSingleTry;
  }


  public void setIsSingleTry(Boolean isSingleTry) {
    this.isSingleTry = isSingleTry;
  }


  public ExternalTaskSuccessMessage result(Object result) {
    
    this.result = result;
    return this;
  }

   /**
   * The result of the ExternalTask.
   * @return result
  **/
  @ApiModelProperty(required = true, value = "The result of the ExternalTask.")
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getResult() {
    return result;
  }


  public void setResult(Object result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalTaskSuccessMessage externalTaskSuccessMessage = (ExternalTaskSuccessMessage) o;
    return Objects.equals(this.correlationId, externalTaskSuccessMessage.correlationId) &&
        Objects.equals(this.processDefinitionId, externalTaskSuccessMessage.processDefinitionId) &&
        Objects.equals(this.processModelId, externalTaskSuccessMessage.processModelId) &&
        Objects.equals(this.processModelName, externalTaskSuccessMessage.processModelName) &&
        Objects.equals(this.processInstanceId, externalTaskSuccessMessage.processInstanceId) &&
        Objects.equals(this.parentProcessInstanceId, externalTaskSuccessMessage.parentProcessInstanceId) &&
        Objects.equals(this.flowNodeId, externalTaskSuccessMessage.flowNodeId) &&
        Objects.equals(this.flowNodeName, externalTaskSuccessMessage.flowNodeName) &&
        Objects.equals(this.flowNodeType, externalTaskSuccessMessage.flowNodeType) &&
        Objects.equals(this.flowNodeInstanceId, externalTaskSuccessMessage.flowNodeInstanceId) &&
        Objects.equals(this.ownerId, externalTaskSuccessMessage.ownerId) &&
        Objects.equals(this.previousFlowNodeInstanceId, externalTaskSuccessMessage.previousFlowNodeInstanceId) &&
        Objects.equals(this.currentToken, externalTaskSuccessMessage.currentToken) &&
        Objects.equals(this.eventType, externalTaskSuccessMessage.eventType) &&
        Objects.equals(this.eventName, externalTaskSuccessMessage.eventName) &&
        Objects.equals(this.customCorrelationId, externalTaskSuccessMessage.customCorrelationId) &&
        Objects.equals(this.externalTaskId, externalTaskSuccessMessage.externalTaskId) &&
        Objects.equals(this.topic, externalTaskSuccessMessage.topic) &&
        Objects.equals(this.isSingleTry, externalTaskSuccessMessage.isSingleTry) &&
        Objects.equals(this.result, externalTaskSuccessMessage.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(correlationId, processDefinitionId, processModelId, processModelName, processInstanceId, parentProcessInstanceId, flowNodeId, flowNodeName, flowNodeType, flowNodeInstanceId, ownerId, previousFlowNodeInstanceId, currentToken, eventType, eventName, customCorrelationId, externalTaskId, topic, isSingleTry, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalTaskSuccessMessage {\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    processModelName: ").append(toIndentedString(processModelName)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    parentProcessInstanceId: ").append(toIndentedString(parentProcessInstanceId)).append("\n");
    sb.append("    flowNodeId: ").append(toIndentedString(flowNodeId)).append("\n");
    sb.append("    flowNodeName: ").append(toIndentedString(flowNodeName)).append("\n");
    sb.append("    flowNodeType: ").append(toIndentedString(flowNodeType)).append("\n");
    sb.append("    flowNodeInstanceId: ").append(toIndentedString(flowNodeInstanceId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    previousFlowNodeInstanceId: ").append(toIndentedString(previousFlowNodeInstanceId)).append("\n");
    sb.append("    currentToken: ").append(toIndentedString(currentToken)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    customCorrelationId: ").append(toIndentedString(customCorrelationId)).append("\n");
    sb.append("    externalTaskId: ").append(toIndentedString(externalTaskId)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    isSingleTry: ").append(toIndentedString(isSingleTry)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

