/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A formatted error object representing an ExternalTask error.
 */
@ApiModel(description = "A formatted error object representing an ExternalTask error.")
@JsonPropertyOrder({
  ExternalTaskReusableError.JSON_PROPERTY_CODE,
  ExternalTaskReusableError.JSON_PROPERTY_NAME,
  ExternalTaskReusableError.JSON_PROPERTY_MESSAGE,
  ExternalTaskReusableError.JSON_PROPERTY_ADDITIONAL_INFORMATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ExternalTaskReusableError {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code = null;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_ADDITIONAL_INFORMATION = "additionalInformation";
  private Object additionalInformation;


  public ExternalTaskReusableError code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * The error code of the error.
   * @return code
  **/
  @ApiModelProperty(required = true, value = "The error code of the error.")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public ExternalTaskReusableError name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the error.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the error.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ExternalTaskReusableError message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * The error message of the error.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The error message of the error.")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ExternalTaskReusableError additionalInformation(Object additionalInformation) {
    
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Additional information about the error.
   * @return additionalInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional information about the error.")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAdditionalInformation() {
    return additionalInformation;
  }


  public void setAdditionalInformation(Object additionalInformation) {
    this.additionalInformation = additionalInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalTaskReusableError externalTaskReusableError = (ExternalTaskReusableError) o;
    return Objects.equals(this.code, externalTaskReusableError.code) &&
        Objects.equals(this.name, externalTaskReusableError.name) &&
        Objects.equals(this.message, externalTaskReusableError.message) &&
        Objects.equals(this.additionalInformation, externalTaskReusableError.additionalInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, message, additionalInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalTaskReusableError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

