/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ExternalTaskLockedMessageAllOf
 */
@JsonPropertyOrder({
  ExternalTaskLockedMessageAllOf.JSON_PROPERTY_WORKER_ID,
  ExternalTaskLockedMessageAllOf.JSON_PROPERTY_LOCK_EXPIRATION_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ExternalTaskLockedMessageAllOf {
  public static final String JSON_PROPERTY_WORKER_ID = "workerId";
  private String workerId;

  public static final String JSON_PROPERTY_LOCK_EXPIRATION_TIME = "lockExpirationTime";
  private String lockExpirationTime;


  public ExternalTaskLockedMessageAllOf workerId(String workerId) {
    
    this.workerId = workerId;
    return this;
  }

   /**
   * The ID of the worker that locked the ExternalTask.
   * @return workerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the worker that locked the ExternalTask.")
  @JsonProperty(JSON_PROPERTY_WORKER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkerId() {
    return workerId;
  }


  public void setWorkerId(String workerId) {
    this.workerId = workerId;
  }


  public ExternalTaskLockedMessageAllOf lockExpirationTime(String lockExpirationTime) {
    
    this.lockExpirationTime = lockExpirationTime;
    return this;
  }

   /**
   * The time when the lock expires.
   * @return lockExpirationTime
  **/
  @ApiModelProperty(required = true, value = "The time when the lock expires.")
  @JsonProperty(JSON_PROPERTY_LOCK_EXPIRATION_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLockExpirationTime() {
    return lockExpirationTime;
  }


  public void setLockExpirationTime(String lockExpirationTime) {
    this.lockExpirationTime = lockExpirationTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalTaskLockedMessageAllOf externalTaskLockedMessageAllOf = (ExternalTaskLockedMessageAllOf) o;
    return Objects.equals(this.workerId, externalTaskLockedMessageAllOf.workerId) &&
        Objects.equals(this.lockExpirationTime, externalTaskLockedMessageAllOf.lockExpirationTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workerId, lockExpirationTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalTaskLockedMessageAllOf {\n");
    sb.append("    workerId: ").append(toIndentedString(workerId)).append("\n");
    sb.append("    lockExpirationTime: ").append(toIndentedString(lockExpirationTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

