/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ExternalTaskUnlockedMessageAllOf
 */
@JsonPropertyOrder({
  ExternalTaskUnlockedMessageAllOf.JSON_PROPERTY_EXTERNAL_TASK_ID,
  ExternalTaskUnlockedMessageAllOf.JSON_PROPERTY_TOPIC
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ExternalTaskUnlockedMessageAllOf {
  public static final String JSON_PROPERTY_EXTERNAL_TASK_ID = "externalTaskId";
  private String externalTaskId;

  public static final String JSON_PROPERTY_TOPIC = "topic";
  private String topic;


  public ExternalTaskUnlockedMessageAllOf externalTaskId(String externalTaskId) {
    
    this.externalTaskId = externalTaskId;
    return this;
  }

   /**
   * The ID of the ExternalTask.
   * @return externalTaskId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ExternalTask.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_TASK_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalTaskId() {
    return externalTaskId;
  }


  public void setExternalTaskId(String externalTaskId) {
    this.externalTaskId = externalTaskId;
  }


  public ExternalTaskUnlockedMessageAllOf topic(String topic) {
    
    this.topic = topic;
    return this;
  }

   /**
   * The topic of the ExternalTask.
   * @return topic
  **/
  @ApiModelProperty(required = true, value = "The topic of the ExternalTask.")
  @JsonProperty(JSON_PROPERTY_TOPIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTopic() {
    return topic;
  }


  public void setTopic(String topic) {
    this.topic = topic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalTaskUnlockedMessageAllOf externalTaskUnlockedMessageAllOf = (ExternalTaskUnlockedMessageAllOf) o;
    return Objects.equals(this.externalTaskId, externalTaskUnlockedMessageAllOf.externalTaskId) &&
        Objects.equals(this.topic, externalTaskUnlockedMessageAllOf.topic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalTaskId, topic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalTaskUnlockedMessageAllOf {\n");
    sb.append("    externalTaskId: ").append(toIndentedString(externalTaskId)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

