/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Describes the payload that must be send with a finishExternalTask HTTP POST request.
 */
@ApiModel(description = "Describes the payload that must be send with a finishExternalTask HTTP POST request.")
@JsonPropertyOrder({
  FinishExternalTaskRequestPayload.JSON_PROPERTY_WORKER_ID,
  FinishExternalTaskRequestPayload.JSON_PROPERTY_RESULT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class FinishExternalTaskRequestPayload {
  public static final String JSON_PROPERTY_WORKER_ID = "workerId";
  private String workerId;

  public static final String JSON_PROPERTY_RESULT = "result";
  private Object result;


  public FinishExternalTaskRequestPayload workerId(String workerId) {
    
    this.workerId = workerId;
    return this;
  }

   /**
   * The ID of the worker that wants to finish the task.
   * @return workerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the worker that wants to finish the task.")
  @JsonProperty(JSON_PROPERTY_WORKER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkerId() {
    return workerId;
  }


  public void setWorkerId(String workerId) {
    this.workerId = workerId;
  }


  public FinishExternalTaskRequestPayload result(Object result) {
    
    this.result = result;
    return this;
  }

   /**
   * The result of the task.
   * @return result
  **/
  @ApiModelProperty(example = "{\"foo\":\"bar\"}", required = true, value = "The result of the task.")
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getResult() {
    return result;
  }


  public void setResult(Object result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinishExternalTaskRequestPayload finishExternalTaskRequestPayload = (FinishExternalTaskRequestPayload) o;
    return Objects.equals(this.workerId, finishExternalTaskRequestPayload.workerId) &&
        Objects.equals(this.result, finishExternalTaskRequestPayload.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workerId, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinishExternalTaskRequestPayload {\n");
    sb.append("    workerId: ").append(toIndentedString(workerId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

