/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.FlowNodeInstance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A list of FlowNodeInstances.
 */
@ApiModel(description = "A list of FlowNodeInstances.")
@JsonPropertyOrder({
  FlowNodeInstanceList.JSON_PROPERTY_FLOW_NODE_INSTANCES,
  FlowNodeInstanceList.JSON_PROPERTY_TOTAL_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class FlowNodeInstanceList {
  public static final String JSON_PROPERTY_FLOW_NODE_INSTANCES = "flowNodeInstances";
  private List<FlowNodeInstance> flowNodeInstances = new ArrayList<FlowNodeInstance>();

  public static final String JSON_PROPERTY_TOTAL_COUNT = "totalCount";
  private BigDecimal totalCount;


  public FlowNodeInstanceList flowNodeInstances(List<FlowNodeInstance> flowNodeInstances) {
    
    this.flowNodeInstances = flowNodeInstances;
    return this;
  }

  public FlowNodeInstanceList addFlowNodeInstancesItem(FlowNodeInstance flowNodeInstancesItem) {
    this.flowNodeInstances.add(flowNodeInstancesItem);
    return this;
  }

   /**
   * The FlowNodeInstances.
   * @return flowNodeInstances
  **/
  @ApiModelProperty(required = true, value = "The FlowNodeInstances.")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_INSTANCES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<FlowNodeInstance> getFlowNodeInstances() {
    return flowNodeInstances;
  }


  public void setFlowNodeInstances(List<FlowNodeInstance> flowNodeInstances) {
    this.flowNodeInstances = flowNodeInstances;
  }


  public FlowNodeInstanceList totalCount(BigDecimal totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * The total number of FlowNodeInstances.
   * @return totalCount
  **/
  @ApiModelProperty(required = true, value = "The total number of FlowNodeInstances.")
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(BigDecimal totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowNodeInstanceList flowNodeInstanceList = (FlowNodeInstanceList) o;
    return Objects.equals(this.flowNodeInstances, flowNodeInstanceList.flowNodeInstances) &&
        Objects.equals(this.totalCount, flowNodeInstanceList.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowNodeInstances, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowNodeInstanceList {\n");
    sb.append("    flowNodeInstances: ").append(toIndentedString(flowNodeInstances)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

