/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.BpmnType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * FlowNodeViewModelAllOf
 */
@JsonPropertyOrder({
  FlowNodeViewModelAllOf.JSON_PROPERTY_NAME,
  FlowNodeViewModelAllOf.JSON_PROPERTY_FLOW_NODE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class FlowNodeViewModelAllOf {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_FLOW_NODE_TYPE = "flowNodeType";
  private BpmnType flowNodeType;


  public FlowNodeViewModelAllOf name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the FlowNode.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the FlowNode.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public FlowNodeViewModelAllOf flowNodeType(BpmnType flowNodeType) {
    
    this.flowNodeType = flowNodeType;
    return this;
  }

   /**
   * Get flowNodeType
   * @return flowNodeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BpmnType getFlowNodeType() {
    return flowNodeType;
  }


  public void setFlowNodeType(BpmnType flowNodeType) {
    this.flowNodeType = flowNodeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowNodeViewModelAllOf flowNodeViewModelAllOf = (FlowNodeViewModelAllOf) o;
    return Objects.equals(this.name, flowNodeViewModelAllOf.name) &&
        Objects.equals(this.flowNodeType, flowNodeViewModelAllOf.flowNodeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, flowNodeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowNodeViewModelAllOf {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    flowNodeType: ").append(toIndentedString(flowNodeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

