/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.BpmnType;
import io.miragon.processcube.client.model.EventType;
import io.miragon.processcube.client.model.FlowNodeInstanceState;
import io.miragon.processcube.client.model.ProcessToken;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A FlowNodeInstance.
 */
@ApiModel(description = "A FlowNodeInstance.")
@JsonPropertyOrder({
  FlowNodeInstance.JSON_PROPERTY_FLOW_NODE_INSTANCE_ID,
  FlowNodeInstance.JSON_PROPERTY_FLOW_NODE_ID,
  FlowNodeInstance.JSON_PROPERTY_FLOW_NODE_NAME,
  FlowNodeInstance.JSON_PROPERTY_FLOW_NODE_LANE,
  FlowNodeInstance.JSON_PROPERTY_FLOW_NODE_TYPE,
  FlowNodeInstance.JSON_PROPERTY_EVENT_TYPE,
  FlowNodeInstance.JSON_PROPERTY_PREVIOUS_FLOW_NODE_INSTANCE_ID,
  FlowNodeInstance.JSON_PROPERTY_PARENT_PROCESS_INSTANCE_ID,
  FlowNodeInstance.JSON_PROPERTY_STATE,
  FlowNodeInstance.JSON_PROPERTY_PROCESS_DEFINITION_ID,
  FlowNodeInstance.JSON_PROPERTY_PROCESS_MODEL_ID,
  FlowNodeInstance.JSON_PROPERTY_PROCESS_INSTANCE_ID,
  FlowNodeInstance.JSON_PROPERTY_CORRELATION_ID,
  FlowNodeInstance.JSON_PROPERTY_TOKENS,
  FlowNodeInstance.JSON_PROPERTY_OWNER_ID,
  FlowNodeInstance.JSON_PROPERTY_ERROR,
  FlowNodeInstance.JSON_PROPERTY_STARTED_AT,
  FlowNodeInstance.JSON_PROPERTY_FINISHED_AT,
  FlowNodeInstance.JSON_PROPERTY_TRIGGERED_BY_FLOW_NODE_INSTANCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class FlowNodeInstance {
  public static final String JSON_PROPERTY_FLOW_NODE_INSTANCE_ID = "flowNodeInstanceId";
  private String flowNodeInstanceId;

  public static final String JSON_PROPERTY_FLOW_NODE_ID = "flowNodeId";
  private String flowNodeId;

  public static final String JSON_PROPERTY_FLOW_NODE_NAME = "flowNodeName";
  private String flowNodeName;

  public static final String JSON_PROPERTY_FLOW_NODE_LANE = "flowNodeLane";
  private String flowNodeLane;

  public static final String JSON_PROPERTY_FLOW_NODE_TYPE = "flowNodeType";
  private BpmnType flowNodeType;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  private EventType eventType;

  public static final String JSON_PROPERTY_PREVIOUS_FLOW_NODE_INSTANCE_ID = "previousFlowNodeInstanceId";
  private String previousFlowNodeInstanceId;

  public static final String JSON_PROPERTY_PARENT_PROCESS_INSTANCE_ID = "parentProcessInstanceId";
  private String parentProcessInstanceId;

  public static final String JSON_PROPERTY_STATE = "state";
  private FlowNodeInstanceState state;

  public static final String JSON_PROPERTY_PROCESS_DEFINITION_ID = "processDefinitionId";
  private String processDefinitionId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_PROCESS_INSTANCE_ID = "processInstanceId";
  private String processInstanceId;

  public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
  private String correlationId;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  private List<ProcessToken> tokens = new ArrayList<ProcessToken>();

  public static final String JSON_PROPERTY_OWNER_ID = "ownerId";
  private String ownerId;

  public static final String JSON_PROPERTY_ERROR = "error";
  private Object error;

  public static final String JSON_PROPERTY_STARTED_AT = "startedAt";
  private String startedAt;

  public static final String JSON_PROPERTY_FINISHED_AT = "finishedAt";
  private String finishedAt;

  public static final String JSON_PROPERTY_TRIGGERED_BY_FLOW_NODE_INSTANCE = "triggeredByFlowNodeInstance";
  private FlowNodeInstance triggeredByFlowNodeInstance;


  public FlowNodeInstance flowNodeInstanceId(String flowNodeInstanceId) {
    
    this.flowNodeInstanceId = flowNodeInstanceId;
    return this;
  }

   /**
   * The ID of the FlowNodeInstance
   * @return flowNodeInstanceId
  **/
  @ApiModelProperty(required = true, value = "The ID of the FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlowNodeInstanceId() {
    return flowNodeInstanceId;
  }


  public void setFlowNodeInstanceId(String flowNodeInstanceId) {
    this.flowNodeInstanceId = flowNodeInstanceId;
  }


  public FlowNodeInstance flowNodeId(String flowNodeId) {
    
    this.flowNodeId = flowNodeId;
    return this;
  }

   /**
   * The ID of the FlowNode
   * @return flowNodeId
  **/
  @ApiModelProperty(required = true, value = "The ID of the FlowNode")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlowNodeId() {
    return flowNodeId;
  }


  public void setFlowNodeId(String flowNodeId) {
    this.flowNodeId = flowNodeId;
  }


  public FlowNodeInstance flowNodeName(String flowNodeName) {
    
    this.flowNodeName = flowNodeName;
    return this;
  }

   /**
   * The name of the FlowNode
   * @return flowNodeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the FlowNode")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowNodeName() {
    return flowNodeName;
  }


  public void setFlowNodeName(String flowNodeName) {
    this.flowNodeName = flowNodeName;
  }


  public FlowNodeInstance flowNodeLane(String flowNodeLane) {
    
    this.flowNodeLane = flowNodeLane;
    return this;
  }

   /**
   * The name of the FlowNode&#39;s lane that contains this FlowNodeInstance
   * @return flowNodeLane
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the FlowNode's lane that contains this FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_LANE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowNodeLane() {
    return flowNodeLane;
  }


  public void setFlowNodeLane(String flowNodeLane) {
    this.flowNodeLane = flowNodeLane;
  }


  public FlowNodeInstance flowNodeType(BpmnType flowNodeType) {
    
    this.flowNodeType = flowNodeType;
    return this;
  }

   /**
   * Get flowNodeType
   * @return flowNodeType
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BpmnType getFlowNodeType() {
    return flowNodeType;
  }


  public void setFlowNodeType(BpmnType flowNodeType) {
    this.flowNodeType = flowNodeType;
  }


  public FlowNodeInstance eventType(EventType eventType) {
    
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventType getEventType() {
    return eventType;
  }


  public void setEventType(EventType eventType) {
    this.eventType = eventType;
  }


  public FlowNodeInstance previousFlowNodeInstanceId(String previousFlowNodeInstanceId) {
    
    this.previousFlowNodeInstanceId = previousFlowNodeInstanceId;
    return this;
  }

   /**
   * The ID of the FlowNodeInstance that was executed before this one.
   * @return previousFlowNodeInstanceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the FlowNodeInstance that was executed before this one.")
  @JsonProperty(JSON_PROPERTY_PREVIOUS_FLOW_NODE_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviousFlowNodeInstanceId() {
    return previousFlowNodeInstanceId;
  }


  public void setPreviousFlowNodeInstanceId(String previousFlowNodeInstanceId) {
    this.previousFlowNodeInstanceId = previousFlowNodeInstanceId;
  }


  public FlowNodeInstance parentProcessInstanceId(String parentProcessInstanceId) {
    
    this.parentProcessInstanceId = parentProcessInstanceId;
    return this;
  }

   /**
   * The ID of the parent ProcessInstance, if this FlowNodeInstance within is a sub process.
   * @return parentProcessInstanceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the parent ProcessInstance, if this FlowNodeInstance within is a sub process.")
  @JsonProperty(JSON_PROPERTY_PARENT_PROCESS_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentProcessInstanceId() {
    return parentProcessInstanceId;
  }


  public void setParentProcessInstanceId(String parentProcessInstanceId) {
    this.parentProcessInstanceId = parentProcessInstanceId;
  }


  public FlowNodeInstance state(FlowNodeInstanceState state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FlowNodeInstanceState getState() {
    return state;
  }


  public void setState(FlowNodeInstanceState state) {
    this.state = state;
  }


  public FlowNodeInstance processDefinitionId(String processDefinitionId) {
    
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * The ID of the ProcessDefinition that contains this FlowNodeInstance
   * @return processDefinitionId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessDefinition that contains this FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessDefinitionId() {
    return processDefinitionId;
  }


  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }


  public FlowNodeInstance processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel that contains this FlowNodeInstance
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel that contains this FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public FlowNodeInstance processInstanceId(String processInstanceId) {
    
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * The ID of the ProcessInstance that contains this FlowNodeInstance
   * @return processInstanceId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessInstance that contains this FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessInstanceId() {
    return processInstanceId;
  }


  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }


  public FlowNodeInstance correlationId(String correlationId) {
    
    this.correlationId = correlationId;
    return this;
  }

   /**
   * The ID of the Correlation that contains this FlowNodeInstance
   * @return correlationId
  **/
  @ApiModelProperty(required = true, value = "The ID of the Correlation that contains this FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_CORRELATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCorrelationId() {
    return correlationId;
  }


  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }


  public FlowNodeInstance tokens(List<ProcessToken> tokens) {
    
    this.tokens = tokens;
    return this;
  }

  public FlowNodeInstance addTokensItem(ProcessToken tokensItem) {
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * The ProcessToken of the FlowNodeInstance
   * @return tokens
  **/
  @ApiModelProperty(required = true, value = "The ProcessToken of the FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProcessToken> getTokens() {
    return tokens;
  }


  public void setTokens(List<ProcessToken> tokens) {
    this.tokens = tokens;
  }


  public FlowNodeInstance ownerId(String ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * The ID of the user that owns this FlowNodeInstance
   * @return ownerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the user that owns this FlowNodeInstance")
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  public FlowNodeInstance error(Object error) {
    
    this.error = error;
    return this;
  }

   /**
   * The error that occured during execution of the FlowNodeInstance (if any).
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The error that occured during execution of the FlowNodeInstance (if any).")
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getError() {
    return error;
  }


  public void setError(Object error) {
    this.error = error;
  }


  public FlowNodeInstance startedAt(String startedAt) {
    
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The date when the FlowNodeInstance was started.
   * @return startedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when the FlowNodeInstance was started.")
  @JsonProperty(JSON_PROPERTY_STARTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartedAt() {
    return startedAt;
  }


  public void setStartedAt(String startedAt) {
    this.startedAt = startedAt;
  }


  public FlowNodeInstance finishedAt(String finishedAt) {
    
    this.finishedAt = finishedAt;
    return this;
  }

   /**
   * The date when the FlowNodeInstance was finished.
   * @return finishedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when the FlowNodeInstance was finished.")
  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFinishedAt() {
    return finishedAt;
  }


  public void setFinishedAt(String finishedAt) {
    this.finishedAt = finishedAt;
  }


  public FlowNodeInstance triggeredByFlowNodeInstance(FlowNodeInstance triggeredByFlowNodeInstance) {
    
    this.triggeredByFlowNodeInstance = triggeredByFlowNodeInstance;
    return this;
  }

   /**
   * Get triggeredByFlowNodeInstance
   * @return triggeredByFlowNodeInstance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRIGGERED_BY_FLOW_NODE_INSTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FlowNodeInstance getTriggeredByFlowNodeInstance() {
    return triggeredByFlowNodeInstance;
  }


  public void setTriggeredByFlowNodeInstance(FlowNodeInstance triggeredByFlowNodeInstance) {
    this.triggeredByFlowNodeInstance = triggeredByFlowNodeInstance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowNodeInstance flowNodeInstance = (FlowNodeInstance) o;
    return Objects.equals(this.flowNodeInstanceId, flowNodeInstance.flowNodeInstanceId) &&
        Objects.equals(this.flowNodeId, flowNodeInstance.flowNodeId) &&
        Objects.equals(this.flowNodeName, flowNodeInstance.flowNodeName) &&
        Objects.equals(this.flowNodeLane, flowNodeInstance.flowNodeLane) &&
        Objects.equals(this.flowNodeType, flowNodeInstance.flowNodeType) &&
        Objects.equals(this.eventType, flowNodeInstance.eventType) &&
        Objects.equals(this.previousFlowNodeInstanceId, flowNodeInstance.previousFlowNodeInstanceId) &&
        Objects.equals(this.parentProcessInstanceId, flowNodeInstance.parentProcessInstanceId) &&
        Objects.equals(this.state, flowNodeInstance.state) &&
        Objects.equals(this.processDefinitionId, flowNodeInstance.processDefinitionId) &&
        Objects.equals(this.processModelId, flowNodeInstance.processModelId) &&
        Objects.equals(this.processInstanceId, flowNodeInstance.processInstanceId) &&
        Objects.equals(this.correlationId, flowNodeInstance.correlationId) &&
        Objects.equals(this.tokens, flowNodeInstance.tokens) &&
        Objects.equals(this.ownerId, flowNodeInstance.ownerId) &&
        Objects.equals(this.error, flowNodeInstance.error) &&
        Objects.equals(this.startedAt, flowNodeInstance.startedAt) &&
        Objects.equals(this.finishedAt, flowNodeInstance.finishedAt) &&
        Objects.equals(this.triggeredByFlowNodeInstance, flowNodeInstance.triggeredByFlowNodeInstance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowNodeInstanceId, flowNodeId, flowNodeName, flowNodeLane, flowNodeType, eventType, previousFlowNodeInstanceId, parentProcessInstanceId, state, processDefinitionId, processModelId, processInstanceId, correlationId, tokens, ownerId, error, startedAt, finishedAt, triggeredByFlowNodeInstance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowNodeInstance {\n");
    sb.append("    flowNodeInstanceId: ").append(toIndentedString(flowNodeInstanceId)).append("\n");
    sb.append("    flowNodeId: ").append(toIndentedString(flowNodeId)).append("\n");
    sb.append("    flowNodeName: ").append(toIndentedString(flowNodeName)).append("\n");
    sb.append("    flowNodeLane: ").append(toIndentedString(flowNodeLane)).append("\n");
    sb.append("    flowNodeType: ").append(toIndentedString(flowNodeType)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    previousFlowNodeInstanceId: ").append(toIndentedString(previousFlowNodeInstanceId)).append("\n");
    sb.append("    parentProcessInstanceId: ").append(toIndentedString(parentProcessInstanceId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    triggeredByFlowNodeInstance: ").append(toIndentedString(triggeredByFlowNodeInstance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

