/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.BaseElementViewModel;
import io.miragon.processcube.client.model.BpmnType;
import io.miragon.processcube.client.model.FlowNodeViewModelAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A FlowNode.
 */
@ApiModel(description = "A FlowNode.")
@JsonPropertyOrder({
  FlowNodeViewModel.JSON_PROPERTY_ID,
  FlowNodeViewModel.JSON_PROPERTY_CUSTOM_PROPERTIES,
  FlowNodeViewModel.JSON_PROPERTY_DOCUMENTATION,
  FlowNodeViewModel.JSON_PROPERTY_PROCESS_MODEL_ID,
  FlowNodeViewModel.JSON_PROPERTY_PROCESS_MODEL_NAME,
  FlowNodeViewModel.JSON_PROPERTY_NAME,
  FlowNodeViewModel.JSON_PROPERTY_FLOW_NODE_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class FlowNodeViewModel {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CUSTOM_PROPERTIES = "customProperties";
  private Map<String, String> customProperties = new HashMap<String, String>();

  public static final String JSON_PROPERTY_DOCUMENTATION = "documentation";
  private List<String> documentation = null;

  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_PROCESS_MODEL_NAME = "processModelName";
  private String processModelName;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_FLOW_NODE_TYPE = "flowNodeType";
  private BpmnType flowNodeType;


  public FlowNodeViewModel id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the BaseElement.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The ID of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public FlowNodeViewModel customProperties(Map<String, String> customProperties) {
    
    this.customProperties = customProperties;
    return this;
  }

  public FlowNodeViewModel putCustomPropertiesItem(String key, String customPropertiesItem) {
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * The custom properties of the BaseElement.
   * @return customProperties
  **/
  @ApiModelProperty(required = true, value = "The custom properties of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, String> getCustomProperties() {
    return customProperties;
  }


  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }


  public FlowNodeViewModel documentation(List<String> documentation) {
    
    this.documentation = documentation;
    return this;
  }

  public FlowNodeViewModel addDocumentationItem(String documentationItem) {
    if (this.documentation == null) {
      this.documentation = new ArrayList<String>();
    }
    this.documentation.add(documentationItem);
    return this;
  }

   /**
   * The documentation of the BaseElement.
   * @return documentation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The documentation of the BaseElement.")
  @JsonProperty(JSON_PROPERTY_DOCUMENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDocumentation() {
    return documentation;
  }


  public void setDocumentation(List<String> documentation) {
    this.documentation = documentation;
  }


  public FlowNodeViewModel processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel that contains the BaseElement.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel that contains the BaseElement.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public FlowNodeViewModel processModelName(String processModelName) {
    
    this.processModelName = processModelName;
    return this;
  }

   /**
   * The name of the ProcessModel that contains the BaseElement.
   * @return processModelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the ProcessModel that contains the BaseElement.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessModelName() {
    return processModelName;
  }


  public void setProcessModelName(String processModelName) {
    this.processModelName = processModelName;
  }


  public FlowNodeViewModel name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the FlowNode.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the FlowNode.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public FlowNodeViewModel flowNodeType(BpmnType flowNodeType) {
    
    this.flowNodeType = flowNodeType;
    return this;
  }

   /**
   * Get flowNodeType
   * @return flowNodeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BpmnType getFlowNodeType() {
    return flowNodeType;
  }


  public void setFlowNodeType(BpmnType flowNodeType) {
    this.flowNodeType = flowNodeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowNodeViewModel flowNodeViewModel = (FlowNodeViewModel) o;
    return Objects.equals(this.id, flowNodeViewModel.id) &&
        Objects.equals(this.customProperties, flowNodeViewModel.customProperties) &&
        Objects.equals(this.documentation, flowNodeViewModel.documentation) &&
        Objects.equals(this.processModelId, flowNodeViewModel.processModelId) &&
        Objects.equals(this.processModelName, flowNodeViewModel.processModelName) &&
        Objects.equals(this.name, flowNodeViewModel.name) &&
        Objects.equals(this.flowNodeType, flowNodeViewModel.flowNodeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customProperties, documentation, processModelId, processModelName, name, flowNodeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowNodeViewModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    processModelName: ").append(toIndentedString(processModelName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    flowNodeType: ").append(toIndentedString(flowNodeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

