/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ExternalTaskBpmnError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Describes the payload that must be send with a handleBpmnError HTTP POST request.
 */
@ApiModel(description = "Describes the payload that must be send with a handleBpmnError HTTP POST request.")
@JsonPropertyOrder({
  HandleBpmnErrorRequestPayload.JSON_PROPERTY_WORKER_ID,
  HandleBpmnErrorRequestPayload.JSON_PROPERTY_BPMN_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class HandleBpmnErrorRequestPayload {
  public static final String JSON_PROPERTY_WORKER_ID = "workerId";
  private String workerId;

  public static final String JSON_PROPERTY_BPMN_ERROR = "bpmnError";
  private ExternalTaskBpmnError bpmnError = null;


  public HandleBpmnErrorRequestPayload workerId(String workerId) {
    
    this.workerId = workerId;
    return this;
  }

   /**
   * The ID of the worker that wants to handle the BPMN error.
   * @return workerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the worker that wants to handle the BPMN error.")
  @JsonProperty(JSON_PROPERTY_WORKER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkerId() {
    return workerId;
  }


  public void setWorkerId(String workerId) {
    this.workerId = workerId;
  }


  public HandleBpmnErrorRequestPayload bpmnError(ExternalTaskBpmnError bpmnError) {
    
    this.bpmnError = bpmnError;
    return this;
  }

   /**
   * Get bpmnError
   * @return bpmnError
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BPMN_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ExternalTaskBpmnError getBpmnError() {
    return bpmnError;
  }


  public void setBpmnError(ExternalTaskBpmnError bpmnError) {
    this.bpmnError = bpmnError;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandleBpmnErrorRequestPayload handleBpmnErrorRequestPayload = (HandleBpmnErrorRequestPayload) o;
    return Objects.equals(this.workerId, handleBpmnErrorRequestPayload.workerId) &&
        Objects.equals(this.bpmnError, handleBpmnErrorRequestPayload.bpmnError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workerId, bpmnError);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandleBpmnErrorRequestPayload {\n");
    sb.append("    workerId: ").append(toIndentedString(workerId)).append("\n");
    sb.append("    bpmnError: ").append(toIndentedString(bpmnError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

