/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ExternalTaskError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Describes the payload that must be send with a handleExternalTaskError HTTP POST request.
 */
@ApiModel(description = "Describes the payload that must be send with a handleExternalTaskError HTTP POST request.")
@JsonPropertyOrder({
  HandleExternalTaskErrorRequestPayload.JSON_PROPERTY_WORKER_ID,
  HandleExternalTaskErrorRequestPayload.JSON_PROPERTY_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class HandleExternalTaskErrorRequestPayload {
  public static final String JSON_PROPERTY_WORKER_ID = "workerId";
  private String workerId;

  public static final String JSON_PROPERTY_ERROR = "error";
  private ExternalTaskError error;


  public HandleExternalTaskErrorRequestPayload workerId(String workerId) {
    
    this.workerId = workerId;
    return this;
  }

   /**
   * The ID of the worker that wants to handle the BPMN error.
   * @return workerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the worker that wants to handle the BPMN error.")
  @JsonProperty(JSON_PROPERTY_WORKER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWorkerId() {
    return workerId;
  }


  public void setWorkerId(String workerId) {
    this.workerId = workerId;
  }


  public HandleExternalTaskErrorRequestPayload error(ExternalTaskError error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExternalTaskError getError() {
    return error;
  }


  public void setError(ExternalTaskError error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandleExternalTaskErrorRequestPayload handleExternalTaskErrorRequestPayload = (HandleExternalTaskErrorRequestPayload) o;
    return Objects.equals(this.workerId, handleExternalTaskErrorRequestPayload.workerId) &&
        Objects.equals(this.error, handleExternalTaskErrorRequestPayload.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workerId, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandleExternalTaskErrorRequestPayload {\n");
    sb.append("    workerId: ").append(toIndentedString(workerId)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

