/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Contains information about an identity.
 */
@ApiModel(description = "Contains information about an identity.")
@JsonPropertyOrder({
  Identity.JSON_PROPERTY_TOKEN,
  Identity.JSON_PROPERTY_USER_ID,
  Identity.JSON_PROPERTY_ANONYMOUS_SESSION_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class Identity {
  public static final String JSON_PROPERTY_TOKEN = "token";
  private String token;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public static final String JSON_PROPERTY_ANONYMOUS_SESSION_ID = "anonymousSessionId";
  private String anonymousSessionId;


  public Identity token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * The ID of the user to which this identiy belongs.
   * @return token
  **/
  @ApiModelProperty(required = true, value = "The ID of the user to which this identiy belongs.")
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public Identity userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the auth token&#39;s owner.
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "The ID of the auth token's owner.")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public Identity anonymousSessionId(String anonymousSessionId) {
    
    this.anonymousSessionId = anonymousSessionId;
    return this;
  }

   /**
   * The ID of an anonymous session.
   * @return anonymousSessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of an anonymous session.")
  @JsonProperty(JSON_PROPERTY_ANONYMOUS_SESSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAnonymousSessionId() {
    return anonymousSessionId;
  }


  public void setAnonymousSessionId(String anonymousSessionId) {
    this.anonymousSessionId = anonymousSessionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Identity identity = (Identity) o;
    return Objects.equals(this.token, identity.token) &&
        Objects.equals(this.userId, identity.userId) &&
        Objects.equals(this.anonymousSessionId, identity.anonymousSessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, userId, anonymousSessionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Identity {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    anonymousSessionId: ").append(toIndentedString(anonymousSessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

