/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * InlineObject1
 */
@JsonPropertyOrder({
  InlineObject1.JSON_PROPERTY_ACTUAL_OWNER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class InlineObject1 {
  public static final String JSON_PROPERTY_ACTUAL_OWNER_ID = "actualOwnerId";
  private String actualOwnerId;


  public InlineObject1 actualOwnerId(String actualOwnerId) {
    
    this.actualOwnerId = actualOwnerId;
    return this;
  }

   /**
   * The ID of the User who reserves the UserTask.
   * @return actualOwnerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "myUser_12345678", value = "The ID of the User who reserves the UserTask.")
  @JsonProperty(JSON_PROPERTY_ACTUAL_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActualOwnerId() {
    return actualOwnerId;
  }


  public void setActualOwnerId(String actualOwnerId) {
    this.actualOwnerId = actualOwnerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject1 inlineObject1 = (InlineObject1) o;
    return Objects.equals(this.actualOwnerId, inlineObject1.actualOwnerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actualOwnerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject1 {\n");
    sb.append("    actualOwnerId: ").append(toIndentedString(actualOwnerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

