/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * InlineObject3
 */
@JsonPropertyOrder({
  InlineObject3.JSON_PROPERTY_NEW_START_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class InlineObject3 {
  public static final String JSON_PROPERTY_NEW_START_TOKEN = "newStartToken";
  private Object newStartToken;


  public InlineObject3 newStartToken(Object newStartToken) {
    
    this.newStartToken = newStartToken;
    return this;
  }

   /**
   * The new start token for the ProcessInstance.
   * @return newStartToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The new start token for the ProcessInstance.")
  @JsonProperty(JSON_PROPERTY_NEW_START_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getNewStartToken() {
    return newStartToken;
  }


  public void setNewStartToken(Object newStartToken) {
    this.newStartToken = newStartToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject3 inlineObject3 = (InlineObject3) o;
    return Objects.equals(this.newStartToken, inlineObject3.newStartToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newStartToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject3 {\n");
    sb.append("    newStartToken: ").append(toIndentedString(newStartToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

