/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * MetadataChangedMessageAllOf
 */
@JsonPropertyOrder({
  MetadataChangedMessageAllOf.JSON_PROPERTY_CHANGED_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class MetadataChangedMessageAllOf {
  public static final String JSON_PROPERTY_CHANGED_METADATA = "changedMetadata";
  private Map<String, String> changedMetadata = null;


  public MetadataChangedMessageAllOf changedMetadata(Map<String, String> changedMetadata) {
    
    this.changedMetadata = changedMetadata;
    return this;
  }

  public MetadataChangedMessageAllOf putChangedMetadataItem(String key, String changedMetadataItem) {
    if (this.changedMetadata == null) {
      this.changedMetadata = new HashMap<String, String>();
    }
    this.changedMetadata.put(key, changedMetadataItem);
    return this;
  }

   /**
   * The changed metadata.
   * @return changedMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The changed metadata.")
  @JsonProperty(JSON_PROPERTY_CHANGED_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getChangedMetadata() {
    return changedMetadata;
  }


  public void setChangedMetadata(Map<String, String> changedMetadata) {
    this.changedMetadata = changedMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataChangedMessageAllOf metadataChangedMessageAllOf = (MetadataChangedMessageAllOf) o;
    return Objects.equals(this.changedMetadata, metadataChangedMessageAllOf.changedMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataChangedMessageAllOf {\n");
    sb.append("    changedMetadata: ").append(toIndentedString(changedMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

