/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The message that is sent whenever a Process was flagged as executable or not executable.
 */
@ApiModel(description = "The message that is sent whenever a Process was flagged as executable or not executable.")
@JsonPropertyOrder({
  ProcessIsExecutableChangedMessage.JSON_PROPERTY_PROCESS_MODEL_ID,
  ProcessIsExecutableChangedMessage.JSON_PROPERTY_IS_EXECUTABLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessIsExecutableChangedMessage {
  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_IS_EXECUTABLE = "isExecutable";
  private Boolean isExecutable;


  public ProcessIsExecutableChangedMessage processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * Contains the ID of the Process Model whose executable state was changed.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "Contains the ID of the Process Model whose executable state was changed.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public ProcessIsExecutableChangedMessage isExecutable(Boolean isExecutable) {
    
    this.isExecutable = isExecutable;
    return this;
  }

   /**
   * Contains the new state of the isExecutable flag.
   * @return isExecutable
  **/
  @ApiModelProperty(required = true, value = "Contains the new state of the isExecutable flag.")
  @JsonProperty(JSON_PROPERTY_IS_EXECUTABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsExecutable() {
    return isExecutable;
  }


  public void setIsExecutable(Boolean isExecutable) {
    this.isExecutable = isExecutable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessIsExecutableChangedMessage processIsExecutableChangedMessage = (ProcessIsExecutableChangedMessage) o;
    return Objects.equals(this.processModelId, processIsExecutableChangedMessage.processModelId) &&
        Objects.equals(this.isExecutable, processIsExecutableChangedMessage.isExecutable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processModelId, isExecutable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessIsExecutableChangedMessage {\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    isExecutable: ").append(toIndentedString(isExecutable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

