/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ProcessStartRequestAllOf
 */
@JsonPropertyOrder({
  ProcessStartRequestAllOf.JSON_PROPERTY_RETURN_ON,
  ProcessStartRequestAllOf.JSON_PROPERTY_END_EVENT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessStartRequestAllOf {
  public static final String JSON_PROPERTY_RETURN_ON = "returnOn";
  private Integer returnOn;

  public static final String JSON_PROPERTY_END_EVENT_ID = "endEventId";
  private String endEventId;


  public ProcessStartRequestAllOf returnOn(Integer returnOn) {
    
    this.returnOn = returnOn;
    return this;
  }

   /**
   * Get returnOn
   * @return returnOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RETURN_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getReturnOn() {
    return returnOn;
  }


  public void setReturnOn(Integer returnOn) {
    this.returnOn = returnOn;
  }


  public ProcessStartRequestAllOf endEventId(String endEventId) {
    
    this.endEventId = endEventId;
    return this;
  }

   /**
   * The ID of an EndEvent that should be awaited. Must be provided, of \&quot;returnOn\&quot; is set to \&quot;CallbackOnEndEventReached\&quot;.
   * @return endEventId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of an EndEvent that should be awaited. Must be provided, of \"returnOn\" is set to \"CallbackOnEndEventReached\".")
  @JsonProperty(JSON_PROPERTY_END_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndEventId() {
    return endEventId;
  }


  public void setEndEventId(String endEventId) {
    this.endEventId = endEventId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessStartRequestAllOf processStartRequestAllOf = (ProcessStartRequestAllOf) o;
    return Objects.equals(this.returnOn, processStartRequestAllOf.returnOn) &&
        Objects.equals(this.endEventId, processStartRequestAllOf.endEventId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnOn, endEventId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessStartRequestAllOf {\n");
    sb.append("    returnOn: ").append(toIndentedString(returnOn)).append("\n");
    sb.append("    endEventId: ").append(toIndentedString(endEventId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

