/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ProcessModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A ProcessDefinition.
 */
@ApiModel(description = "A ProcessDefinition.")
@JsonPropertyOrder({
  ProcessDefinition.JSON_PROPERTY_PROCESS_DEFINITION_ID,
  ProcessDefinition.JSON_PROPERTY_XML,
  ProcessDefinition.JSON_PROPERTY_HASH,
  ProcessDefinition.JSON_PROPERTY_PROCESS_MODELS,
  ProcessDefinition.JSON_PROPERTY_DEPLOYED_AT,
  ProcessDefinition.JSON_PROPERTY_DEPLOYED_BY_USER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessDefinition {
  public static final String JSON_PROPERTY_PROCESS_DEFINITION_ID = "processDefinitionId";
  private String processDefinitionId;

  public static final String JSON_PROPERTY_XML = "xml";
  private String xml;

  public static final String JSON_PROPERTY_HASH = "hash";
  private String hash;

  public static final String JSON_PROPERTY_PROCESS_MODELS = "processModels";
  private List<ProcessModel> processModels = new ArrayList<ProcessModel>();

  public static final String JSON_PROPERTY_DEPLOYED_AT = "deployedAt";
  private String deployedAt;

  public static final String JSON_PROPERTY_DEPLOYED_BY_USER_ID = "deployedByUserId";
  private String deployedByUserId;


  public ProcessDefinition processDefinitionId(String processDefinitionId) {
    
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * The ID of the ProcessDefinition.
   * @return processDefinitionId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessDefinition.")
  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessDefinitionId() {
    return processDefinitionId;
  }


  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }


  public ProcessDefinition xml(String xml) {
    
    this.xml = xml;
    return this;
  }

   /**
   * The XML of the ProcessDefinition.
   * @return xml
  **/
  @ApiModelProperty(required = true, value = "The XML of the ProcessDefinition.")
  @JsonProperty(JSON_PROPERTY_XML)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getXml() {
    return xml;
  }


  public void setXml(String xml) {
    this.xml = xml;
  }


  public ProcessDefinition hash(String hash) {
    
    this.hash = hash;
    return this;
  }

   /**
   * The hash of the ProcessDefinition.
   * @return hash
  **/
  @ApiModelProperty(required = true, value = "The hash of the ProcessDefinition.")
  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHash() {
    return hash;
  }


  public void setHash(String hash) {
    this.hash = hash;
  }


  public ProcessDefinition processModels(List<ProcessModel> processModels) {
    
    this.processModels = processModels;
    return this;
  }

  public ProcessDefinition addProcessModelsItem(ProcessModel processModelsItem) {
    this.processModels.add(processModelsItem);
    return this;
  }

   /**
   * The ProcessModels contained in the ProcessDefinition.
   * @return processModels
  **/
  @ApiModelProperty(required = true, value = "The ProcessModels contained in the ProcessDefinition.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODELS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProcessModel> getProcessModels() {
    return processModels;
  }


  public void setProcessModels(List<ProcessModel> processModels) {
    this.processModels = processModels;
  }


  public ProcessDefinition deployedAt(String deployedAt) {
    
    this.deployedAt = deployedAt;
    return this;
  }

   /**
   * The date when the ProcessDefinition was deployed.
   * @return deployedAt
  **/
  @ApiModelProperty(required = true, value = "The date when the ProcessDefinition was deployed.")
  @JsonProperty(JSON_PROPERTY_DEPLOYED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeployedAt() {
    return deployedAt;
  }


  public void setDeployedAt(String deployedAt) {
    this.deployedAt = deployedAt;
  }


  public ProcessDefinition deployedByUserId(String deployedByUserId) {
    
    this.deployedByUserId = deployedByUserId;
    return this;
  }

   /**
   * The ID of the user who deployed the ProcessDefinition.
   * @return deployedByUserId
  **/
  @ApiModelProperty(required = true, value = "The ID of the user who deployed the ProcessDefinition.")
  @JsonProperty(JSON_PROPERTY_DEPLOYED_BY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeployedByUserId() {
    return deployedByUserId;
  }


  public void setDeployedByUserId(String deployedByUserId) {
    this.deployedByUserId = deployedByUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessDefinition processDefinition = (ProcessDefinition) o;
    return Objects.equals(this.processDefinitionId, processDefinition.processDefinitionId) &&
        Objects.equals(this.xml, processDefinition.xml) &&
        Objects.equals(this.hash, processDefinition.hash) &&
        Objects.equals(this.processModels, processDefinition.processModels) &&
        Objects.equals(this.deployedAt, processDefinition.deployedAt) &&
        Objects.equals(this.deployedByUserId, processDefinition.deployedByUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processDefinitionId, xml, hash, processModels, deployedAt, deployedByUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessDefinition {\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    xml: ").append(toIndentedString(xml)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    processModels: ").append(toIndentedString(processModels)).append("\n");
    sb.append("    deployedAt: ").append(toIndentedString(deployedAt)).append("\n");
    sb.append("    deployedByUserId: ").append(toIndentedString(deployedByUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

