/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The options to use for starting a ProcessInstance.
 */
@ApiModel(description = "The options to use for starting a ProcessInstance.")
@JsonPropertyOrder({
  ProcessStartOptions.JSON_PROPERTY_PROCESS_MODEL_ID,
  ProcessStartOptions.JSON_PROPERTY_START_EVENT_ID,
  ProcessStartOptions.JSON_PROPERTY_CORRELATION_ID,
  ProcessStartOptions.JSON_PROPERTY_INITIAL_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessStartOptions {
  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_START_EVENT_ID = "startEventId";
  private String startEventId;

  public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
  private String correlationId;

  public static final String JSON_PROPERTY_INITIAL_TOKEN = "initialToken";
  private Object initialToken;


  public ProcessStartOptions processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel to start.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel to start.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public ProcessStartOptions startEventId(String startEventId) {
    
    this.startEventId = startEventId;
    return this;
  }

   /**
   * The ID of a StartEvent at which the ProcessInstance should start.
   * @return startEventId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of a StartEvent at which the ProcessInstance should start.")
  @JsonProperty(JSON_PROPERTY_START_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartEventId() {
    return startEventId;
  }


  public void setStartEventId(String startEventId) {
    this.startEventId = startEventId;
  }


  public ProcessStartOptions correlationId(String correlationId) {
    
    this.correlationId = correlationId;
    return this;
  }

   /**
   * A correlation ID to use for the ProcessInstance.
   * @return correlationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A correlation ID to use for the ProcessInstance.")
  @JsonProperty(JSON_PROPERTY_CORRELATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCorrelationId() {
    return correlationId;
  }


  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }


  public ProcessStartOptions initialToken(Object initialToken) {
    
    this.initialToken = initialToken;
    return this;
  }

   /**
   * The token to use for an initial ProcessToken.
   * @return initialToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The token to use for an initial ProcessToken.")
  @JsonProperty(JSON_PROPERTY_INITIAL_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getInitialToken() {
    return initialToken;
  }


  public void setInitialToken(Object initialToken) {
    this.initialToken = initialToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessStartOptions processStartOptions = (ProcessStartOptions) o;
    return Objects.equals(this.processModelId, processStartOptions.processModelId) &&
        Objects.equals(this.startEventId, processStartOptions.startEventId) &&
        Objects.equals(this.correlationId, processStartOptions.correlationId) &&
        Objects.equals(this.initialToken, processStartOptions.initialToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processModelId, startEventId, correlationId, initialToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessStartOptions {\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    startEventId: ").append(toIndentedString(startEventId)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    initialToken: ").append(toIndentedString(initialToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

