/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ProcessTokenType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A process token describes the state of a FlowNode during a specific point in its life (i.e. onEnter, onExit, etc.).
 */
@ApiModel(description = "A process token describes the state of a FlowNode during a specific point in its life (i.e. onEnter, onExit, etc.).")
@JsonPropertyOrder({
  ProcessToken.JSON_PROPERTY_FLOW_NODE_INSTANCE_ID,
  ProcessToken.JSON_PROPERTY_CREATED_AT,
  ProcessToken.JSON_PROPERTY_TYPE,
  ProcessToken.JSON_PROPERTY_PAYLOAD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessToken {
  public static final String JSON_PROPERTY_FLOW_NODE_INSTANCE_ID = "flowNodeInstanceId";
  private String flowNodeInstanceId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private String createdAt;

  public static final String JSON_PROPERTY_TYPE = "type";
  private ProcessTokenType type;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  private Object payload;


  public ProcessToken flowNodeInstanceId(String flowNodeInstanceId) {
    
    this.flowNodeInstanceId = flowNodeInstanceId;
    return this;
  }

   /**
   * The ID of the FlowNodeInstance that this token belongs to.
   * @return flowNodeInstanceId
  **/
  @ApiModelProperty(required = true, value = "The ID of the FlowNodeInstance that this token belongs to.")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlowNodeInstanceId() {
    return flowNodeInstanceId;
  }


  public void setFlowNodeInstanceId(String flowNodeInstanceId) {
    this.flowNodeInstanceId = flowNodeInstanceId;
  }


  public ProcessToken createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The point in time at which this token was created.
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "The point in time at which this token was created.")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public ProcessToken type(ProcessTokenType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProcessTokenType getType() {
    return type;
  }


  public void setType(ProcessTokenType type) {
    this.type = type;
  }


  public ProcessToken payload(Object payload) {
    
    this.payload = payload;
    return this;
  }

   /**
   * The payload of the token.
   * @return payload
  **/
  @ApiModelProperty(required = true, value = "The payload of the token.")
  @JsonProperty(JSON_PROPERTY_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getPayload() {
    return payload;
  }


  public void setPayload(Object payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessToken processToken = (ProcessToken) o;
    return Objects.equals(this.flowNodeInstanceId, processToken.flowNodeInstanceId) &&
        Objects.equals(this.createdAt, processToken.createdAt) &&
        Objects.equals(this.type, processToken.type) &&
        Objects.equals(this.payload, processToken.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flowNodeInstanceId, createdAt, type, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessToken {\n");
    sb.append("    flowNodeInstanceId: ").append(toIndentedString(flowNodeInstanceId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

