/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ProcessInstance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A list of ProcessInstances.
 */
@ApiModel(description = "A list of ProcessInstances.")
@JsonPropertyOrder({
  ProcessInstanceList.JSON_PROPERTY_PROCESS_INSTANCES,
  ProcessInstanceList.JSON_PROPERTY_TOTAL_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessInstanceList {
  public static final String JSON_PROPERTY_PROCESS_INSTANCES = "processInstances";
  private List<ProcessInstance> processInstances = new ArrayList<ProcessInstance>();

  public static final String JSON_PROPERTY_TOTAL_COUNT = "totalCount";
  private BigDecimal totalCount;


  public ProcessInstanceList processInstances(List<ProcessInstance> processInstances) {
    
    this.processInstances = processInstances;
    return this;
  }

  public ProcessInstanceList addProcessInstancesItem(ProcessInstance processInstancesItem) {
    this.processInstances.add(processInstancesItem);
    return this;
  }

   /**
   * The process instances
   * @return processInstances
  **/
  @ApiModelProperty(required = true, value = "The process instances")
  @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ProcessInstance> getProcessInstances() {
    return processInstances;
  }


  public void setProcessInstances(List<ProcessInstance> processInstances) {
    this.processInstances = processInstances;
  }


  public ProcessInstanceList totalCount(BigDecimal totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * The total number of process instances
   * @return totalCount
  **/
  @ApiModelProperty(required = true, value = "The total number of process instances")
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(BigDecimal totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessInstanceList processInstanceList = (ProcessInstanceList) o;
    return Objects.equals(this.processInstances, processInstanceList.processInstances) &&
        Objects.equals(this.totalCount, processInstanceList.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processInstances, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessInstanceList {\n");
    sb.append("    processInstances: ").append(toIndentedString(processInstances)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

