/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.miragon.processcube.client.model.ProcessStartOptions;
import io.miragon.processcube.client.model.ProcessStartRequestAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The request object to use for starting a ProcessInstance.
 */
@ApiModel(description = "The request object to use for starting a ProcessInstance.")
@JsonPropertyOrder({
  ProcessStartRequest.JSON_PROPERTY_PROCESS_MODEL_ID,
  ProcessStartRequest.JSON_PROPERTY_START_EVENT_ID,
  ProcessStartRequest.JSON_PROPERTY_CORRELATION_ID,
  ProcessStartRequest.JSON_PROPERTY_INITIAL_TOKEN,
  ProcessStartRequest.JSON_PROPERTY_RETURN_ON,
  ProcessStartRequest.JSON_PROPERTY_END_EVENT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class ProcessStartRequest {
  public static final String JSON_PROPERTY_PROCESS_MODEL_ID = "processModelId";
  private String processModelId;

  public static final String JSON_PROPERTY_START_EVENT_ID = "startEventId";
  private String startEventId;

  public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
  private String correlationId;

  public static final String JSON_PROPERTY_INITIAL_TOKEN = "initialToken";
  private Object initialToken;

  public static final String JSON_PROPERTY_RETURN_ON = "returnOn";
  private Integer returnOn;

  public static final String JSON_PROPERTY_END_EVENT_ID = "endEventId";
  private String endEventId;


  public ProcessStartRequest processModelId(String processModelId) {
    
    this.processModelId = processModelId;
    return this;
  }

   /**
   * The ID of the ProcessModel to start.
   * @return processModelId
  **/
  @ApiModelProperty(required = true, value = "The ID of the ProcessModel to start.")
  @JsonProperty(JSON_PROPERTY_PROCESS_MODEL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProcessModelId() {
    return processModelId;
  }


  public void setProcessModelId(String processModelId) {
    this.processModelId = processModelId;
  }


  public ProcessStartRequest startEventId(String startEventId) {
    
    this.startEventId = startEventId;
    return this;
  }

   /**
   * The ID of a StartEvent at which the ProcessInstance should start.
   * @return startEventId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of a StartEvent at which the ProcessInstance should start.")
  @JsonProperty(JSON_PROPERTY_START_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartEventId() {
    return startEventId;
  }


  public void setStartEventId(String startEventId) {
    this.startEventId = startEventId;
  }


  public ProcessStartRequest correlationId(String correlationId) {
    
    this.correlationId = correlationId;
    return this;
  }

   /**
   * A correlation ID to use for the ProcessInstance.
   * @return correlationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A correlation ID to use for the ProcessInstance.")
  @JsonProperty(JSON_PROPERTY_CORRELATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCorrelationId() {
    return correlationId;
  }


  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }


  public ProcessStartRequest initialToken(Object initialToken) {
    
    this.initialToken = initialToken;
    return this;
  }

   /**
   * The token to use for an initial ProcessToken.
   * @return initialToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The token to use for an initial ProcessToken.")
  @JsonProperty(JSON_PROPERTY_INITIAL_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getInitialToken() {
    return initialToken;
  }


  public void setInitialToken(Object initialToken) {
    this.initialToken = initialToken;
  }


  public ProcessStartRequest returnOn(Integer returnOn) {
    
    this.returnOn = returnOn;
    return this;
  }

   /**
   * Get returnOn
   * @return returnOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RETURN_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getReturnOn() {
    return returnOn;
  }


  public void setReturnOn(Integer returnOn) {
    this.returnOn = returnOn;
  }


  public ProcessStartRequest endEventId(String endEventId) {
    
    this.endEventId = endEventId;
    return this;
  }

   /**
   * The ID of an EndEvent that should be awaited. Must be provided, of \&quot;returnOn\&quot; is set to \&quot;CallbackOnEndEventReached\&quot;.
   * @return endEventId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of an EndEvent that should be awaited. Must be provided, of \"returnOn\" is set to \"CallbackOnEndEventReached\".")
  @JsonProperty(JSON_PROPERTY_END_EVENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndEventId() {
    return endEventId;
  }


  public void setEndEventId(String endEventId) {
    this.endEventId = endEventId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessStartRequest processStartRequest = (ProcessStartRequest) o;
    return Objects.equals(this.processModelId, processStartRequest.processModelId) &&
        Objects.equals(this.startEventId, processStartRequest.startEventId) &&
        Objects.equals(this.correlationId, processStartRequest.correlationId) &&
        Objects.equals(this.initialToken, processStartRequest.initialToken) &&
        Objects.equals(this.returnOn, processStartRequest.returnOn) &&
        Objects.equals(this.endEventId, processStartRequest.endEventId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processModelId, startEventId, correlationId, initialToken, returnOn, endEventId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessStartRequest {\n");
    sb.append("    processModelId: ").append(toIndentedString(processModelId)).append("\n");
    sb.append("    startEventId: ").append(toIndentedString(startEventId)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    initialToken: ").append(toIndentedString(initialToken)).append("\n");
    sb.append("    returnOn: ").append(toIndentedString(returnOn)).append("\n");
    sb.append("    endEventId: ").append(toIndentedString(endEventId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

