/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The parameters to use for a search.
 */
@ApiModel(description = "The parameters to use for a search.")
@JsonPropertyOrder({
  SearchParams.JSON_PROPERTY_SEARCH_STRING,
  SearchParams.JSON_PROPERTY_CASE_SENSITIVE,
  SearchParams.JSON_PROPERTY_PARTIAL_MATCH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class SearchParams {
  public static final String JSON_PROPERTY_SEARCH_STRING = "searchString";
  private String searchString;

  public static final String JSON_PROPERTY_CASE_SENSITIVE = "caseSensitive";
  private Boolean caseSensitive;

  public static final String JSON_PROPERTY_PARTIAL_MATCH = "partialMatch";
  private Boolean partialMatch;


  public SearchParams searchString(String searchString) {
    
    this.searchString = searchString;
    return this;
  }

   /**
   * The string to search for.
   * @return searchString
  **/
  @ApiModelProperty(required = true, value = "The string to search for.")
  @JsonProperty(JSON_PROPERTY_SEARCH_STRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSearchString() {
    return searchString;
  }


  public void setSearchString(String searchString) {
    this.searchString = searchString;
  }


  public SearchParams caseSensitive(Boolean caseSensitive) {
    
    this.caseSensitive = caseSensitive;
    return this;
  }

   /**
   * A flag to indicate, whether the search should be case sensitive.
   * @return caseSensitive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A flag to indicate, whether the search should be case sensitive.")
  @JsonProperty(JSON_PROPERTY_CASE_SENSITIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCaseSensitive() {
    return caseSensitive;
  }


  public void setCaseSensitive(Boolean caseSensitive) {
    this.caseSensitive = caseSensitive;
  }


  public SearchParams partialMatch(Boolean partialMatch) {
    
    this.partialMatch = partialMatch;
    return this;
  }

   /**
   * A flag to indicate, whether the search should be a partial match.
   * @return partialMatch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A flag to indicate, whether the search should be a partial match.")
  @JsonProperty(JSON_PROPERTY_PARTIAL_MATCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPartialMatch() {
    return partialMatch;
  }


  public void setPartialMatch(Boolean partialMatch) {
    this.partialMatch = partialMatch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchParams searchParams = (SearchParams) o;
    return Objects.equals(this.searchString, searchParams.searchString) &&
        Objects.equals(this.caseSensitive, searchParams.caseSensitive) &&
        Objects.equals(this.partialMatch, searchParams.partialMatch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchString, caseSensitive, partialMatch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchParams {\n");
    sb.append("    searchString: ").append(toIndentedString(searchString)).append("\n");
    sb.append("    caseSensitive: ").append(toIndentedString(caseSensitive)).append("\n");
    sb.append("    partialMatch: ").append(toIndentedString(partialMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

