/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * StartEventViewModelAllOf
 */
@JsonPropertyOrder({
  StartEventViewModelAllOf.JSON_PROPERTY_TIMER_TYPE,
  StartEventViewModelAllOf.JSON_PROPERTY_TIMER_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class StartEventViewModelAllOf {
  public static final String JSON_PROPERTY_TIMER_TYPE = "timerType";
  private String timerType;

  public static final String JSON_PROPERTY_TIMER_VALUE = "timerValue";
  private String timerValue;


  public StartEventViewModelAllOf timerType(String timerType) {
    
    this.timerType = timerType;
    return this;
  }

   /**
   * The type of the timer.
   * @return timerType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of the timer.")
  @JsonProperty(JSON_PROPERTY_TIMER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimerType() {
    return timerType;
  }


  public void setTimerType(String timerType) {
    this.timerType = timerType;
  }


  public StartEventViewModelAllOf timerValue(String timerValue) {
    
    this.timerValue = timerValue;
    return this;
  }

   /**
   * The value of the timer.
   * @return timerValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value of the timer.")
  @JsonProperty(JSON_PROPERTY_TIMER_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimerValue() {
    return timerValue;
  }


  public void setTimerValue(String timerValue) {
    this.timerValue = timerValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StartEventViewModelAllOf startEventViewModelAllOf = (StartEventViewModelAllOf) o;
    return Objects.equals(this.timerType, startEventViewModelAllOf.timerType) &&
        Objects.equals(this.timerValue, startEventViewModelAllOf.timerValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timerType, timerValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StartEventViewModelAllOf {\n");
    sb.append("    timerType: ").append(toIndentedString(timerType)).append("\n");
    sb.append("    timerValue: ").append(toIndentedString(timerValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

