/*
 * 5Minds Engine API
 * This is the swagger ui documentation of the 5Minds Engine API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.miragon.processcube.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The user metadata
 */
@ApiModel(description = "The user metadata")
@JsonPropertyOrder({
  UserMetadata.JSON_PROPERTY_KEY,
  UserMetadata.JSON_PROPERTY_VALUE,
  UserMetadata.JSON_PROPERTY_PROCESS_INSTANCE_SCOPE,
  UserMetadata.JSON_PROPERTY_FLOW_NODE_INSTANCE_SCOPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-19T14:39:29.278702+02:00[Europe/Berlin]")
public class UserMetadata {
  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value = null;

  public static final String JSON_PROPERTY_PROCESS_INSTANCE_SCOPE = "processInstanceScope";
  private String processInstanceScope;

  public static final String JSON_PROPERTY_FLOW_NODE_INSTANCE_SCOPE = "flowNodeInstanceScope";
  private String flowNodeInstanceScope;


  public UserMetadata key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * The key of the user metadata
   * @return key
  **/
  @ApiModelProperty(required = true, value = "The key of the user metadata")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public UserMetadata value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * The value of the user metadata
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The value of the user metadata")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String  getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public UserMetadata processInstanceScope(String processInstanceScope) {
    
    this.processInstanceScope = processInstanceScope;
    return this;
  }

   /**
   * The scope of the user metadata
   * @return processInstanceScope
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The scope of the user metadata")
  @JsonProperty(JSON_PROPERTY_PROCESS_INSTANCE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessInstanceScope() {
    return processInstanceScope;
  }


  public void setProcessInstanceScope(String processInstanceScope) {
    this.processInstanceScope = processInstanceScope;
  }


  public UserMetadata flowNodeInstanceScope(String flowNodeInstanceScope) {
    
    this.flowNodeInstanceScope = flowNodeInstanceScope;
    return this;
  }

   /**
   * The scope of the user metadata
   * @return flowNodeInstanceScope
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The scope of the user metadata")
  @JsonProperty(JSON_PROPERTY_FLOW_NODE_INSTANCE_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowNodeInstanceScope() {
    return flowNodeInstanceScope;
  }


  public void setFlowNodeInstanceScope(String flowNodeInstanceScope) {
    this.flowNodeInstanceScope = flowNodeInstanceScope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserMetadata userMetadata = (UserMetadata) o;
    return Objects.equals(this.key, userMetadata.key) &&
        Objects.equals(this.value, userMetadata.value) &&
        Objects.equals(this.processInstanceScope, userMetadata.processInstanceScope) &&
        Objects.equals(this.flowNodeInstanceScope, userMetadata.flowNodeInstanceScope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value, processInstanceScope, flowNodeInstanceScope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserMetadata {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    processInstanceScope: ").append(toIndentedString(processInstanceScope)).append("\n");
    sb.append("    flowNodeInstanceScope: ").append(toIndentedString(flowNodeInstanceScope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

